"""Helpers for the SQLite -> PostgreSQL migration tests.

``mirror_schema`` creates PostgreSQL tables that mirror a SQLite database's ordinary tables
(declared-type affinity -> PostgreSQL type, INTEGER PRIMARY KEY -> identity column, float32 BLOB
tables listed in migrate_to_pg.VECTOR_COLUMNS get their vector column). It stands in for the
workspace baseline in copier tests that exercise arbitrary SQLite shapes.
"""
from contextlib import closing
from pathlib import Path

from psycopg import sql

from tam_db.contracts import EXTENSIONS_SCHEMA
from team_memory.migrate_to_pg import VECTOR_COLUMNS, open_source, source_tables


def pg_type(declared: str) -> str:
    declared = declared.upper()
    if "INT" in declared or "BOOL" in declared:
        return "bigint"
    if any(marker in declared for marker in ("REAL", "FLOA", "DOUB")):
        return "double precision"
    if "BLOB" in declared:
        return "bytea"
    return "text"


def mirror_schema(source: Path, connection, schema: str, *, create_schema: bool = True) -> None:
    with closing(open_source(source)) as db:
        tables = source_tables(db)
        columns = {table: db.execute(f'PRAGMA table_info("{table}")').fetchall() for table in tables}
    with connection.transaction():
        if create_schema:
            connection.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))
        for table in tables:
            info = columns[table]
            keys = sorted((row for row in info if row[5]), key=lambda row: row[5])
            single_integer_key = len(keys) == 1 and keys[0][2].upper() == "INTEGER"
            parts = []
            for _, name, declared, _, _, position in info:
                if single_integer_key and position:
                    parts.append(sql.SQL("{} bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY").format(
                        sql.Identifier(name)))
                else:
                    parts.append(sql.SQL("{} {}").format(sql.Identifier(name), sql.SQL(pg_type(declared))))
            for vector_table, column in VECTOR_COLUMNS:
                if vector_table == table:
                    parts.append(sql.SQL("{} {}.vector").format(sql.Identifier(column), sql.Identifier(EXTENSIONS_SCHEMA)))
            if keys and not single_integer_key:
                parts.append(sql.SQL("PRIMARY KEY ({})").format(
                    sql.SQL(", ").join(sql.Identifier(row[1]) for row in keys)))
            connection.execute(sql.SQL("CREATE TABLE {} ({})").format(
                sql.Identifier(schema, table), sql.SQL(", ").join(parts)))



def create_quarantine(connection, schema: str) -> None:
    """The workspace baseline's migration_quarantine table, for mirrored test schemas."""
    connection.execute(sql.SQL(
        "CREATE TABLE {} (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_table text NOT NULL, "
        "source_pk text NOT NULL, row jsonb NOT NULL, reason text NOT NULL, migrated_at text NOT NULL)").format(
            sql.Identifier(schema, "migration_quarantine")))
