"""Backend-neutral database access for team tests (SQLite files or the PostgreSQL control plane).

Team tests used to open identity.db, learning.db and workspaces/<key>/memory.db directly. These
helpers go through the Registry's control plane instead, so the same test runs on both backends
(``--backend=both``), and give PostgreSQL-only tests a non-superuser admin role that has exactly
the privileges plan 1.4 requires.
"""
import re
import secrets
from collections.abc import Iterator, Sequence
from contextlib import contextmanager

import pytest
from pydantic import SecretStr

from tam_db.contracts import EXTENSIONS_SCHEMA, Backend, ControlKind
from team_memory.database_contracts import DatabaseDsn
from team_memory.registry import Registry

ADMIN_ROLE_PREFIX = "tam_admin_"
SQLITE_ROWID_KEY = re.compile(r"\bINTEGER PRIMARY KEY\b", re.IGNORECASE)
PG_IDENTITY_KEY = "bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def backend_of(registry: Registry) -> Backend:
    return registry.plane.backend


def skip_unless_sqlite(registry_or_backend: Registry | Backend, reason: str) -> None:
    backend = registry_or_backend if isinstance(registry_or_backend, Backend) else backend_of(registry_or_backend)
    if backend is not Backend.SQLITE:
        pytest.skip(reason)


@contextmanager
def identity(registry: Registry, write: bool = False):
    with registry.plane.connect(ControlKind.IDENTITY, write=write) as db:
        yield db


@contextmanager
def learning(registry: Registry):
    with registry.plane.connect(ControlKind.LEARNING, write=True) as db:
        yield db


def _pg_statement(sql: str) -> str:
    return SQLITE_ROWID_KEY.sub(PG_IDENTITY_KEY, sql).replace("?", "%s")


def seed_workspace(registry: Registry, key: str, schema: str, rows: Sequence[tuple[str, Sequence[object]]]) -> None:
    """Create a workspace with the given (SQLite-dialect) tables and rows, readable by gateway readers.

    SQLite: ``workspaces/<key>/memory.db``. PostgreSQL: the provisioned workspace schema, written as
    the workspace's own role; ``INTEGER PRIMARY KEY`` becomes an identity column and ``?`` a
    placeholder, which is all the test schemas need.
    """
    import sqlite3
    from contextlib import closing

    workspaces = registry.plane.workspaces
    if backend_of(registry) is Backend.SQLITE:
        workspaces.ensure(key)
        with closing(sqlite3.connect(registry.root / "workspaces" / key / "memory.db")) as db:
            db.executescript(schema)
            for sql, params in rows:
                db.execute(sql, tuple(params))
            db.commit()
        return
    import psycopg

    # The test's own tables instead of the workspace migrations.
    workspaces.ensure(key, migrate=False)
    with psycopg.connect(workspaces.store_database(key).url) as db:
        for statement in filter(str.strip, schema.split(";")):
            db.execute(_pg_statement(statement))
        for sql, params in rows:
            db.execute(_pg_statement(sql), tuple(params))


@contextmanager
def pg_admin(database, *, superuser: bool) -> Iterator[str]:
    """URL of the TAM admin role for ``database`` (a tests.pg_support.PgDatabase).

    superuser=True: the server's bootstrap superuser (what team_backend uses). False: a fresh
    LOGIN role with CREATEROLE and CREATE on the database only, the minimum plan 1.4 asks the
    DBA for; the DBA also grants USAGE on schema extensions to PUBLIC.
    """
    import psycopg
    from psycopg import sql

    if superuser:
        yield database.url
        return
    name = ADMIN_ROLE_PREFIX + secrets.token_hex(6)
    password = secrets.token_urlsafe(18)
    with psycopg.connect(database.url, autocommit=True) as connection:
        connection.execute(sql.SQL("CREATE ROLE {} LOGIN CREATEROLE PASSWORD {}").format(
            sql.Identifier(name), sql.Literal(password)))
        connection.execute(sql.SQL("GRANT CREATE ON DATABASE {} TO {}").format(
            sql.Identifier(database.name), sql.Identifier(name)))
        connection.execute(sql.SQL("GRANT USAGE ON SCHEMA {} TO PUBLIC").format(sql.Identifier(EXTENSIONS_SCHEMA)))
    url = DatabaseDsn.parse(database.url).model_copy(update={"user": name, "password": SecretStr(password)}).to_uri()
    try:
        yield url
    finally:
        # Workspace roles were granted to the admin by the admin itself; they go first.
        with psycopg.connect(database.url, autocommit=True) as connection:
            roles = [row[0] for row in connection.execute(
                "SELECT r.rolname FROM pg_auth_members m JOIN pg_roles r ON r.oid = m.roleid "
                "JOIN pg_roles a ON a.oid = m.member WHERE a.rolname = %s AND r.rolname LIKE 'wsr\\_%%'", (name,))]
            for role in (*roles, name):
                connection.execute(sql.SQL("DROP OWNED BY {} CASCADE").format(sql.Identifier(role)))
        with psycopg.connect(database.server.admin_url, autocommit=True) as connection:
            for role in (*roles, name):
                connection.execute(sql.SQL("DROP ROLE IF EXISTS {}").format(sql.Identifier(role)))


def live_worker_lease(registry: Registry, key: str):
    """The lease a running workspace worker holds: a file lock on SQLite, an advisory lock on PostgreSQL."""
    if backend_of(registry) is Backend.SQLITE:
        from team_memory.lifecycle import ServerLease

        return ServerLease(registry.root / "workspaces" / key)
    from team_memory.pg_provision import workspace_lease

    current = registry.plane.current()
    return workspace_lease(current.url, key, current.settings)


def stored_identity_bytes(registry: Registry) -> bytes:
    """Everything the identity store holds at rest: the identity.db file on SQLite, every row of
    every tam_control table (as text) on PostgreSQL. For "secret never stored in clear" checks."""
    if backend_of(registry) is Backend.SQLITE:
        return registry.path.read_bytes()
    import psycopg
    from psycopg import sql

    from tam_db.contracts import CONTROL_SCHEMA

    chunks = []
    with psycopg.connect(registry.plane.current().url) as db:
        tables = [row[0] for row in db.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_schema = %s", (CONTROL_SCHEMA,))]
        for table in tables:
            chunks += [row[0] for row in db.execute(
                sql.SQL("SELECT t::text FROM {} t").format(sql.Identifier(CONTROL_SCHEMA, table)))]
    return "\n".join(chunks).encode("utf-8")
