"""PostgreSQL backup and restore (team_memory.pg_backup)."""
import json
import os
import secrets
import stat
import uuid

import pytest
from pydantic import SecretStr

from tam_db.contracts import schema_for
from team_memory.contracts import Conflict
from team_memory.database_contracts import DatabaseDsn, DsnOrigin

psycopg = pytest.importorskip("psycopg", reason="install the postgres extra: pip install '.[postgres]'")

from psycopg import sql

from team_memory import pg_backup
from tests.pg_support import fresh_database

KEY = "shared"
OTHER_KEY = "team_" + "d" * 64
MASTER_KEY = secrets.token_bytes(32)


def provisioned(url: str, instance_id: str):
    from team_memory.pg_provision import PgProvisioner, PgWorkspaceProvisioner

    PgProvisioner(url).bootstrap(instance_id)
    return PgWorkspaceProvisioner(url, instance_id, MASTER_KEY)


@pytest.fixture
def installation(pg_database):
    instance_id = str(uuid.uuid4())
    workspaces = provisioned(pg_database.url, instance_id)
    workspaces.ensure(KEY)
    workspaces.ensure(OTHER_KEY)
    database = workspaces.store_database(KEY)
    with psycopg.connect(database.url, autocommit=True) as connection:
        connection.execute("CREATE TABLE notes (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                           "content text NOT NULL, embedding extensions.vector)")
        connection.execute("INSERT INTO notes (content, embedding) VALUES ('alpha', '[1,2,3]'), ('beta', NULL)")
    with psycopg.connect(pg_database.url, autocommit=True) as connection:
        connection.execute("INSERT INTO tam_control.users (id, name) VALUES ('anna', 'Anna')")
    return pg_database, instance_id


# Pure units


def test_passfile_holds_the_password_only_while_the_tool_runs(monkeypatch):
    dsn = DatabaseDsn.parse("postgresql://tam:p%3Aw%5Cd@db1:5433,db2/tam?sslmode=require")
    with pg_backup._client_environment(dsn, {"PGPASSWORD": "leak", "PATH": "/bin"}) as env:
        path = env["PGPASSFILE"]
        assert "PGPASSWORD" not in env and env["PATH"] == "/bin"
        assert stat.S_IMODE(os.stat(path).st_mode) == 0o600
        with open(path, encoding="utf-8") as handle:
            assert handle.read().splitlines() == ["*:5433:tam:tam:p\\:w\\\\d", "*:5432:tam:tam:p\\:w\\\\d"]
    assert not os.path.exists(path)
    uri = pg_backup._uri_without_password(dsn)
    assert "p%3Aw" not in uri and uri.startswith("postgresql://tam@db1:5433,db2:5432/tam")


def test_passwordless_dsn_needs_no_passfile():
    dsn = DatabaseDsn.parse("postgresql://tam@db/tam", DsnOrigin.ENV)
    with pg_backup._client_environment(dsn, {}) as env:
        assert "PGPASSFILE" not in env


def test_missing_client_tool_names_the_override_variable(monkeypatch):
    monkeypatch.setattr(pg_backup.shutil, "which", lambda name: None)
    with pytest.raises(Conflict, match="TAM_TEAM_PG_DUMP"):
        pg_backup._tool(pg_backup.PG_DUMP, pg_backup.PG_DUMP_ENV, {})


def test_tool_timeout_is_validated():
    assert pg_backup._timeout({}) == pg_backup.DEFAULT_TOOL_TIMEOUT_SECONDS
    assert pg_backup._timeout({pg_backup.TOOL_TIMEOUT_ENV: "60"}) == 60
    with pytest.raises(Conflict):
        pg_backup._timeout({pg_backup.TOOL_TIMEOUT_ENV: "-1"})


def test_sqlite_snapshots_are_not_postgres_backups(tmp_path):
    (tmp_path / "manifest.json").write_text(json.dumps({"format_version": 1, "databases": []}))
    assert not pg_backup.is_postgres_backup(tmp_path)
    with pytest.raises(Conflict, match="not a PostgreSQL backup"):
        pg_backup.read_manifest(tmp_path)
    assert not pg_backup.is_postgres_backup(tmp_path / "missing")


# PostgreSQL


@pytest.mark.postgres
def test_backup_writes_a_verified_private_dump_with_counts(installation, tmp_path):
    database, instance_id = installation
    dsn = DatabaseDsn.parse(database.url)
    manifest = pg_backup.backup(dsn, tmp_path / "snapshot")
    assert manifest.format_version == 2 and manifest.backend == "postgres"
    assert manifest.instance_id == instance_id and manifest.workspaces == (KEY, OTHER_KEY)
    assert set(manifest.schemas) == {"tam_control", "tam_learning", "tam_compat", schema_for(KEY),
                                     schema_for(OTHER_KEY)}
    counts = {(item.schema_name, item.table): item.rows for item in manifest.counts}
    assert counts[(schema_for(KEY), "notes")] == 2 and counts[("tam_control", "users")] == 1
    snapshot = tmp_path / "snapshot"
    assert stat.S_IMODE(snapshot.stat().st_mode) == 0o700
    assert stat.S_IMODE((snapshot / "tam.dump").stat().st_mode) == 0o600
    assert pg_backup.verify(snapshot) == manifest
    assert pg_backup.is_postgres_backup(snapshot)
    password = dsn.password.get_secret_value()
    assert password not in (snapshot / "manifest.json").read_text()
    with pytest.raises(FileExistsError):
        pg_backup.backup(dsn, snapshot)


@pytest.mark.postgres
def test_verify_rejects_a_modified_dump(installation, tmp_path):
    database, _ = installation
    pg_backup.backup(DatabaseDsn.parse(database.url), tmp_path / "snapshot")
    with (tmp_path / "snapshot" / "tam.dump").open("ab") as handle:
        handle.write(b"x")
    with pytest.raises(Conflict, match="checksum"):
        pg_backup.verify(tmp_path / "snapshot")


@pytest.mark.postgres
def test_backup_refuses_a_database_without_tam(pg_database, tmp_path):
    with pytest.raises(Conflict, match="no TAM installation"):
        pg_backup.backup(DatabaseDsn.parse(pg_database.url), tmp_path / "snapshot")
    assert not (tmp_path / "snapshot").exists()


@pytest.mark.postgres
def test_restore_into_an_empty_database_reprovisions_workspace_roles(installation, tmp_path, pg_server):
    database, instance_id = installation
    pg_backup.backup(DatabaseDsn.parse(database.url), tmp_path / "snapshot")
    with fresh_database(pg_server) as target:
        dsn = DatabaseDsn.parse(target.url)
        from team_memory.pg_provision import PgWorkspaceProvisioner

        # The original database still uses the workspace roles: restoring next to it is refused.
        with pytest.raises(Conflict, match="in use by another database"):
            pg_backup.restore(tmp_path / "snapshot", dsn,
                              lambda: PgWorkspaceProvisioner(target.url, instance_id, MASTER_KEY))
        with psycopg.connect(pg_server.admin_url, autocommit=True) as admin:
            admin.execute(sql.SQL("DROP DATABASE {} WITH (FORCE)").format(sql.Identifier(database.name)))
        manifest = pg_backup.restore(tmp_path / "snapshot", dsn,
                                     lambda: PgWorkspaceProvisioner(target.url, instance_id, MASTER_KEY))
        assert manifest.workspaces == (KEY, OTHER_KEY)
        workspace = PgWorkspaceProvisioner(target.url, instance_id, MASTER_KEY).store_database(KEY)
        with psycopg.connect(workspace.url, autocommit=True) as connection:
            rows = connection.execute("SELECT content, embedding::text FROM notes ORDER BY id").fetchall()
            assert rows == [("alpha", "[1,2,3]"), ("beta", None)]
            new_id = connection.execute("INSERT INTO notes (content) VALUES ('gamma') RETURNING id").fetchone()[0]
            assert new_id == 3
            with pytest.raises(psycopg.errors.InsufficientPrivilege):
                connection.execute(f"SELECT 1 FROM {schema_for(OTHER_KEY)}.knowledge LIMIT 1")
        with psycopg.connect(target.url, autocommit=True) as connection:
            assert connection.execute("SELECT value FROM tam_control.meta WHERE key = 'instance_id'").fetchone()[0] \
                == instance_id
        with pytest.raises(Conflict, match="empty database"):
            pg_backup.restore(tmp_path / "snapshot", dsn,
                              lambda: PgWorkspaceProvisioner(target.url, instance_id, MASTER_KEY))


@pytest.mark.postgres
def test_backup_never_runs_a_workspace_row_security_policy(pg_database, tmp_path):
    """As a non-superuser admin (superusers bypass row security anyway), like a managed PostgreSQL."""
    admin_role, password = "tam_admin_" + secrets.token_hex(4), secrets.token_hex(12)
    with psycopg.connect(pg_database.url, autocommit=True) as superuser:
        superuser.execute(sql.SQL("CREATE ROLE {} LOGIN CREATEROLE PASSWORD {}").format(
            sql.Identifier(admin_role), sql.Literal(password)))
        superuser.execute(sql.SQL("GRANT CONNECT, CREATE ON DATABASE {} TO {}").format(
            sql.Identifier(pg_database.name), sql.Identifier(admin_role)))
        superuser.execute("GRANT USAGE ON SCHEMA extensions TO PUBLIC")
    admin = DatabaseDsn.parse(pg_database.url).model_copy(update={"user": admin_role,
                                                                   "password": SecretStr(password)})
    try:
        workspaces = provisioned(admin.to_uri(), str(uuid.uuid4()))
        workspaces.ensure(KEY)
        workspace = workspaces.store_database(KEY)
        with psycopg.connect(workspace.url, autocommit=True) as connection:
            connection.execute("CREATE TABLE notes (id bigint PRIMARY KEY, content text)")
            connection.execute("INSERT INTO notes VALUES (1, 'row the policy would see')")
            connection.execute("CREATE TABLE policy_log (at text)")
            connection.execute("""CREATE FUNCTION trap() RETURNS boolean LANGUAGE plpgsql AS
                                  $$ BEGIN INSERT INTO policy_log VALUES ('ran'); RETURN true; END $$""")
            connection.execute("ALTER TABLE notes ENABLE ROW LEVEL SECURITY")
            connection.execute("ALTER TABLE notes FORCE ROW LEVEL SECURITY")
            connection.execute("CREATE POLICY trap_policy ON notes USING (trap())")
        with pytest.raises(Conflict, match="row-level security"):
            pg_backup.backup(admin, tmp_path / "snapshot")
        assert not (tmp_path / "snapshot").exists()
        with psycopg.connect(pg_database.url, autocommit=True) as superuser:
            assert superuser.execute(sql.SQL("SELECT count(*) FROM {}").format(
                sql.Identifier(schema_for(KEY), "policy_log"))).fetchone()[0] == 0
    finally:
        with psycopg.connect(pg_database.url, autocommit=True) as superuser:
            superuser.execute(sql.SQL("REASSIGN OWNED BY {} TO CURRENT_USER").format(sql.Identifier(admin_role)))
            superuser.execute(sql.SQL("DROP OWNED BY {}").format(sql.Identifier(admin_role)))
            superuser.execute(sql.SQL("DROP ROLE {}").format(sql.Identifier(admin_role)))
