-- Identity control plane (PostgreSQL port of identity.db, see src/team_memory/registry.py SCHEMA).
-- Applied by team_memory.pg_provision into schema tam_control with search_path set to it.
-- Column names, order and value types match SQLite: timestamps stay ISO-8601 TEXT written by
-- tam_compat.strftime('%Y-%m-%dT%H:%M:%fZ','now'); REAL epochs become double precision; flags stay integers.

CREATE TABLE users (
    id text PRIMARY KEY,
    name text NOT NULL,
    active integer NOT NULL DEFAULT 1,
    org_role text NOT NULL DEFAULT 'member' CHECK (org_role IN ('member', 'company_viewer', 'superadmin')),
    password_hash text,
    created_at text,
    last_login_at text
);

CREATE TABLE teams (
    id text PRIMARY KEY,
    name text NOT NULL
);

CREATE TABLE membership (
    user_id text REFERENCES users (id),
    team_id text REFERENCES teams (id),
    role text NOT NULL CHECK (role IN ('reader', 'editor', 'manager')),
    PRIMARY KEY (user_id, team_id)
);

CREATE TABLE tokens (
    digest text PRIMARY KEY,
    user_id text NOT NULL REFERENCES users (id),
    client text NOT NULL,
    revoked integer NOT NULL DEFAULT 0,
    created_at text
);

CREATE TABLE admin_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at text NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    action text NOT NULL,
    subject text NOT NULL,
    actor text,
    detail text
);

CREATE TABLE invites (
    digest text PRIMARY KEY,
    user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at double precision NOT NULL,
    expires_at double precision NOT NULL,
    used_at double precision,
    created_by text NOT NULL
);
CREATE INDEX invites_user ON invites (user_id);

CREATE TABLE sessions (
    digest text PRIMARY KEY,
    user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    csrf text NOT NULL,
    method text NOT NULL CHECK (method IN ('password', 'token', 'invite')),
    token_digest text,
    created_at double precision NOT NULL,
    last_seen_at double precision NOT NULL,
    expires_at double precision NOT NULL
);
CREATE INDEX sessions_user ON sessions (user_id);

CREATE TABLE login_failures (
    key text PRIMARY KEY,
    failures integer NOT NULL,
    window_start double precision NOT NULL,
    locked_until double precision NOT NULL DEFAULT 0
);

CREATE TABLE login_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at double precision NOT NULL,
    user_id text NOT NULL,
    method text NOT NULL,
    outcome text NOT NULL
);
CREATE INDEX login_log_at ON login_log (at);

CREATE TABLE provider_checks (
    target text NOT NULL,
    provider text NOT NULL,
    ok integer NOT NULL,
    detail text NOT NULL,
    at text NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    PRIMARY KEY (target, provider)
);

CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL,
    secret integer NOT NULL,
    updated_at text NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_by text NOT NULL
);

CREATE TABLE organization (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at text NOT NULL DEFAULT (to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    updated_by text NOT NULL
);

CREATE TABLE setup_tokens (
    digest text PRIMARY KEY,
    created_at double precision NOT NULL,
    expires_at double precision NOT NULL,
    used_at double precision
);

-- Installation identity (plan 4.3): instance_id must equal database.json's before the server starts.
CREATE TABLE meta (
    key text PRIMARY KEY,
    value text NOT NULL
);
