-- Learning control plane (PostgreSQL port of learning.db, see src/team_memory/learning/repository.py).
-- Applied by team_memory.pg_provision into schema tam_learning with search_path set to it.

CREATE TABLE meta (
    key text PRIMARY KEY,
    value text NOT NULL
);

CREATE TABLE curricula (
    team_id text PRIMARY KEY,
    title text NOT NULL,
    revision integer NOT NULL,
    updated_at text NOT NULL,
    updated_by text NOT NULL
);

CREATE TABLE modules (
    id text PRIMARY KEY,
    team_id text NOT NULL REFERENCES curricula (team_id),
    position integer NOT NULL,
    title text NOT NULL,
    summary text NOT NULL,
    pass_threshold double precision NOT NULL,
    max_attempts integer NOT NULL,
    archived integer NOT NULL DEFAULT 0
);
CREATE INDEX modules_team ON modules (team_id, archived, position);

CREATE TABLE lessons (
    id text PRIMARY KEY,
    module_id text NOT NULL REFERENCES modules (id),
    position integer NOT NULL,
    title text NOT NULL,
    body text NOT NULL,
    record_ids text NOT NULL,
    content_hash text NOT NULL DEFAULT '',
    version integer NOT NULL DEFAULT 0,
    resolved_ids text NOT NULL DEFAULT '[]',
    checked_at text,
    archived integer NOT NULL DEFAULT 0
);
CREATE INDEX lessons_module ON lessons (module_id, archived, position);

CREATE TABLE quizzes (
    module_id text PRIMARY KEY REFERENCES modules (id),
    questions text NOT NULL,
    revision integer NOT NULL,
    updated_at text NOT NULL,
    updated_by text NOT NULL
);

CREATE TABLE enrollments (
    team_id text NOT NULL,
    user_id text NOT NULL,
    started_at text NOT NULL,
    PRIMARY KEY (team_id, user_id)
);

CREATE TABLE lesson_progress (
    user_id text NOT NULL,
    lesson_id text NOT NULL REFERENCES lessons (id),
    opened_at text NOT NULL,
    completed_at text,
    first_completed_at text,
    time_spent_seconds integer,
    studied_hash text,
    studied_version integer,
    PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id text NOT NULL,
    module_id text NOT NULL REFERENCES modules (id),
    user_id text NOT NULL,
    quiz_revision integer NOT NULL,
    submitted_at text NOT NULL,
    status text NOT NULL CHECK (status IN ('graded', 'pending_review')),
    score double precision NOT NULL,
    max_score double precision NOT NULL,
    pass_threshold double precision NOT NULL,
    passed integer,
    graded_at text
);
CREATE INDEX attempts_user ON attempts (user_id, module_id, id);

CREATE TABLE attempt_answers (
    attempt_id bigint NOT NULL REFERENCES attempts (id),
    question_id text NOT NULL,
    position integer NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    points double precision NOT NULL,
    score double precision NOT NULL,
    status text NOT NULL CHECK (status IN ('graded', 'pending')),
    grader text CHECK (grader IN ('auto', 'llm', 'manager')),
    comment text NOT NULL DEFAULT '',
    graded_by text,
    graded_at text,
    PRIMARY KEY (attempt_id, question_id)
);

CREATE TABLE learning_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id text NOT NULL,
    user_id text NOT NULL,
    at text NOT NULL,
    event text NOT NULL,
    subject_id text NOT NULL,
    summary text NOT NULL
);
CREATE INDEX learning_log_team ON learning_log (team_id, id);
CREATE INDEX learning_log_user ON learning_log (team_id, user_id, id);

CREATE TABLE personal_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL,
    team_id text NOT NULL,
    content text NOT NULL,
    created_at text NOT NULL,
    delivered_at text,
    outcome text
);
CREATE INDEX personal_outbox_pending ON personal_outbox (user_id, delivered_at, id);

-- Same format as SQLite (uuid4().hex): onboarding note request ids are derived from it.
INSERT INTO meta (key, value) VALUES ('instance_id', replace(gen_random_uuid()::text, '-', ''));
