-- Workspace schema baseline for the PostgreSQL team-server backend.
--
-- Final state of a fresh SQLite memory.db after migrations/001..037 and the
-- Store._schema/_migrate Python ALTERs, applied by tam_db.pg_schema.ensure()
-- inside the workspace schema (the first entry of search_path; extensions such
-- as vector live in schema "extensions", also on search_path). Later workspace
-- changes are 0002_*.sql and up; the SQLite migration history is recorded as
-- rows of the "migrations" table below, exactly as a fresh SQLite store has it.
--
-- Mapping rules (tests/test_pg_schema_parity.py checks them against a fresh
-- SQLite Store):
--   * column order is SQLite's, including columns ALTER TABLE appended, so
--     positional INSERTs keep working;
--   * INTEGER/BOOLEAN -> bigint, TEXT/JSON -> text, REAL -> double precision,
--     BLOB -> bytea; timestamps stay ISO-8601 text;
--   * INTEGER PRIMARY KEY (a rowid alias) -> bigint GENERATED BY DEFAULT AS
--     IDENTITY; ids are never reused;
--   * FOREIGN KEY clauses are not declared: the SQLite store runs with
--     PRAGMA foreign_keys=OFF, so neither the references nor their ON DELETE
--     actions are enforced there. The triggers below carry the integrity rules
--     the store relies on;
--   * the 25 SQLite triggers keep their names and behaviour in PL/pgSQL;
--     RAISE(ABORT, ...) becomes RAISE EXCEPTION (SQLSTATE P0001, surfaced as
--     sqlite3.IntegrityError by tam_db);
--   * the five FTS5 tables become side tables (<table>_tsv) holding the
--     unicode61-equivalent token arrays of each indexed column, maintained by
--     the same trigger names, with GIN indexes for matching and fts_stats for
--     BM25 (memory_core.pg_fts compiles MATCH expressions against them).

-- SQLite strftime('%Y-%m-%dT%H:%M:%SZ', 'now'): statement time in UTC, whole seconds.
CREATE FUNCTION tam_utc_now() RETURNS text
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
$$;

-- SQLite strftime('%Y-%m-%dT%H:%M:%fZ', 'now'): the same with milliseconds.
CREATE FUNCTION tam_utc_now_ms() RETURNS text
LANGUAGE sql STABLE PARALLEL SAFE AS $$
    SELECT to_char(statement_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
$$;

-- knowledge.fts_project: SQLite 'p' || lower(hex(project)); hex(NULL) is ''.
-- convert_to is STABLE only because of the encoding argument; the database
-- encoding is UTF8 by prerequisite, so the result depends on the input alone.
CREATE FUNCTION tam_fts_project_token(project text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT 'p' || COALESCE(encode(convert_to(project, 'UTF8'), 'hex'), '')
$$;

-- Tokens of `value` exactly as the FTS5 unicode61 tokenizer (remove_diacritics=1)
-- produces them: split on every character FTS5 treats as a separator, fold case,
-- then strip diacritics the way FTS5 does (a character-for-character map; the 25
-- combining marks FTS5 drops are deleted). Both tables were derived from SQLite's
-- own tokenizer over every Unicode code point; tests/test_pg_fts.py re-derives them
-- and fails when they drift. Folding runs per token and only on tokens holding a
-- mapped character, so text without diacritics costs one regexp split.
-- Tokens are cut to 500 characters (at most 2000 bytes) because a tsvector lexeme
-- holds at most 2046 bytes; FTS5 has no such limit.
CREATE FUNCTION tam_fts_tokens(value text) RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT COALESCE(array_agg(left(folded, 500) ORDER BY position), '{}')
    FROM (
        SELECT CASE WHEN token ~ '[\u00b5\u00e0-\u00e5\u00e7-\u00ef\u00f1-\u00f6\u00f9-\u00fd\u00ff\u0101\u0103\u0105\u0107\u0109\u010b\u010d\u010f\u0113\u0115\u0117\u0119\u011b\u011d\u011f\u0121\u0123\u0125\u0129\u012b\u012d\u012f\u0135\u0137\u013a\u013c\u013e\u0144\u0146\u0148\u014d\u014f\u0151\u0155\u0157\u0159\u015b\u015d\u015f\u0161\u0163\u0165\u0169\u016b\u016d\u016f\u0171\u0173\u0175\u0177\u017a\u017c\u017e-\u017f\u01a1\u01b0\u01ce\u01d0\u01d2\u01d4\u01e7\u01e9\u01eb\u01f0\u01f5\u01f9\u0201\u0203\u0205\u0207\u0209\u020b\u020d\u020f\u0211\u0213\u0215\u0217\u0219\u021b\u021f\u0227\u0229\u022f\u0233\u0300-\u0304\u0306-\u030c\u030f\u0311\u031b\u0323-\u0328\u032d-\u032e\u0330-\u0331\u03c2\u03d0-\u03d1\u03d5-\u03d6\u03f0-\u03f1\u03f5\u1e01\u1e03\u1e05\u1e07\u1e0b\u1e0d\u1e0f\u1e11\u1e13\u1e19\u1e1b\u1e1f\u1e21\u1e23\u1e25\u1e27\u1e29\u1e2b\u1e2d\u1e31\u1e33\u1e35\u1e37\u1e3b\u1e3d\u1e3f\u1e41\u1e43\u1e45\u1e47\u1e49\u1e4b\u1e55\u1e57\u1e59\u1e5b\u1e5f\u1e61\u1e63\u1e6b\u1e6d\u1e6f\u1e71\u1e73\u1e75\u1e77\u1e7d\u1e7f\u1e81\u1e83\u1e85\u1e87\u1e89\u1e8b\u1e8d\u1e8f\u1e91\u1e93\u1e95-\u1e99\u1e9b\u1ea1\u1ea3\u1eb9\u1ebb\u1ebd\u1ec9\u1ecb\u1ecd\u1ecf\u1ee5\u1ee7\u1ef3\u1ef5\u1ef7\u1ef9\u1fbe]'
                    THEN translate(token, U&'\00B5\00E0\00E1\00E2\00E3\00E4\00E5\00E7\00E8\00E9\00EA\00EB\00EC\00ED\00EE\00EF\00F1\00F2\00F3\00F4\00F5\00F6\00F9\00FA\00FB\00FC\00FD\00FF\0101\0103\0105\0107\0109\010B\010D\010F\0113\0115\0117\0119\011B\011D\011F\0121\0123\0125\0129\012B\012D\012F\0135\0137\013A\013C\013E\0144\0146\0148\014D\014F\0151\0155\0157\0159\015B\015D\015F\0161\0163\0165\0169\016B\016D\016F\0171\0173\0175\0177\017A\017C\017E\017F\01A1\01B0\01CE\01D0\01D2\01D4\01E7\01E9\01EB\01F0\01F5\01F9\0201\0203\0205\0207\0209\020B\020D\020F\0211\0213\0215\0217\0219\021B\021F\0227\0229\022F\0233\03C2\03D0\03D1\03D5\03D6\03F0\03F1\03F5\1E01\1E03\1E05\1E07\1E0B\1E0D\1E0F\1E11\1E13\1E19\1E1B\1E1F\1E21\1E23\1E25\1E27\1E29\1E2B\1E2D\1E31\1E33\1E35\1E37\1E3B\1E3D\1E3F\1E41\1E43\1E45\1E47\1E49\1E4B\1E55\1E57\1E59\1E5B\1E5F\1E61\1E63\1E6B\1E6D\1E6F\1E71\1E73\1E75\1E77\1E7D\1E7F\1E81\1E83\1E85\1E87\1E89\1E8B\1E8D\1E8F\1E91\1E93\1E95\1E96\1E97\1E98\1E99\1E9B\1EA1\1EA3\1EB9\1EBB\1EBD\1EC9\1ECB\1ECD\1ECF\1EE5\1EE7\1EF3\1EF5\1EF7\1EF9\1FBE\0300\0301\0302\0303\0304\0306\0307\0308\0309\030A\030B\030C\030F\0311\031B\0323\0324\0325\0326\0327\0328\032D\032E\0330\0331', U&'\03BC\0061\0061\0061\0061\0061\0061\0063\0065\0065\0065\0065\0069\0069\0069\0069\006E\006F\006F\006F\006F\006F\0075\0075\0075\0075\0079\0079\0061\0061\0061\0063\0063\0063\0063\0064\0065\0065\0065\0065\0065\0067\0067\0067\0067\0068\0069\0069\0069\0069\006A\006B\006C\006C\006C\006E\006E\006E\006F\006F\006F\0072\0072\0072\0073\0073\0073\0073\0074\0074\0075\0075\0075\0075\0075\0075\0077\0079\007A\007A\007A\0073\006F\0075\0061\0069\006F\0075\0067\006B\006F\006A\0067\006E\0061\0061\0065\0065\0069\0069\006F\006F\0072\0072\0075\0075\0073\0074\0068\0061\0065\006F\0079\03C3\03B2\03B8\03C6\03C0\03BA\03C1\03B5\0061\0062\0062\0062\0064\0064\0064\0064\0064\0065\0065\0066\0067\0068\0068\0068\0068\0068\0069\006B\006B\006B\006C\006C\006C\006D\006D\006D\006E\006E\006E\006E\0070\0070\0072\0072\0072\0073\0073\0074\0074\0074\0074\0075\0075\0075\0076\0076\0077\0077\0077\0077\0077\0078\0078\0079\007A\007A\007A\0068\0074\0077\0079\0073\0061\0061\0065\0065\0065\0069\0069\006F\006F\0075\0075\0079\0079\0079\0079\03B9')
                    ELSE token END AS folded,
               position
        FROM regexp_split_to_table(lower(value), '[\u0001-\u002f\u003a-\u0040\u005b-\u0060\u007b-\u00a9\u00ab-\u00b1\u00b4\u00b6-\u00b8\u00bb\u00bf\u00d7\u00f7\u02c2-\u02c5\u02d2-\u02df\u02e5-\u02eb\u02ed\u02ef-\u02ff\u0305\u030d-\u030e\u0310\u0312-\u031a\u031c-\u0322\u0329-\u032c\u032f\u0332-\u036f\u0375\u037e\u0384-\u0385\u0387\u03f6\u0482-\u0489\u055a-\u055f\u0589-\u058a\u058f\u0591-\u05c7\u05f3-\u05f4\u0600-\u0604\u0606-\u061b\u061e-\u061f\u064b-\u065f\u066a-\u066d\u0670\u06d4\u06d6-\u06e4\u06e7-\u06ed\u06fd-\u06fe\u0700-\u070d\u070f\u0711\u0730-\u074a\u07a6-\u07b0\u07eb-\u07f3\u07f6-\u07f9\u0816-\u0819\u081b-\u0823\u0825-\u0827\u0829-\u082d\u0830-\u083e\u0859-\u085b\u085e\u08e4-\u08fe\u0900-\u0903\u093a-\u093c\u093e-\u094f\u0951-\u0957\u0962-\u0965\u0970\u0981-\u0983\u09bc\u09be-\u09c4\u09c7-\u09c8\u09cb-\u09cd\u09d7\u09e2-\u09e3\u09f2-\u09f3\u09fa-\u09fb\u0a01-\u0a03\u0a3c\u0a3e-\u0a42\u0a47-\u0a48\u0a4b-\u0a4d\u0a51\u0a70-\u0a71\u0a75\u0a81-\u0a83\u0abc\u0abe-\u0ac5\u0ac7-\u0ac9\u0acb-\u0acd\u0ae2-\u0ae3\u0af0-\u0af1\u0b01-\u0b03\u0b3c\u0b3e-\u0b44\u0b47-\u0b48\u0b4b-\u0b4d\u0b56-\u0b57\u0b62-\u0b63\u0b70\u0b82\u0bbe-\u0bc2\u0bc6-\u0bc8\u0bca-\u0bcd\u0bd7\u0bf3-\u0bfa\u0c01-\u0c03\u0c3e-\u0c44\u0c46-\u0c48\u0c4a-\u0c4d\u0c55-\u0c56\u0c62-\u0c63\u0c7f\u0c82-\u0c83\u0cbc\u0cbe-\u0cc4\u0cc6-\u0cc8\u0cca-\u0ccd\u0cd5-\u0cd6\u0ce2-\u0ce3\u0d02-\u0d03\u0d3e-\u0d44\u0d46-\u0d48\u0d4a-\u0d4d\u0d57\u0d62-\u0d63\u0d79\u0d82-\u0d83\u0dca\u0dcf-\u0dd4\u0dd6\u0dd8-\u0ddf\u0df2-\u0df4\u0e31\u0e34-\u0e3a\u0e3f\u0e47-\u0e4f\u0e5a-\u0e5b\u0eb1\u0eb4-\u0eb9\u0ebb-\u0ebc\u0ec8-\u0ecd\u0f01-\u0f1f\u0f34-\u0f3f\u0f71-\u0f87\u0f8d-\u0f97\u0f99-\u0fbc\u0fbe-\u0fcc\u0fce-\u0fda\u102b-\u103e\u104a-\u104f\u1056-\u1059\u105e-\u1060\u1062-\u1064\u1067-\u106d\u1071-\u1074\u1082-\u108d\u108f\u109a-\u109f\u10fb\u135d-\u1368\u1390-\u1399\u1400\u166d-\u166e\u1680\u169b-\u169c\u16eb-\u16ed\u1712-\u1714\u1732-\u1736\u1752-\u1753\u1772-\u1773\u17b4-\u17d6\u17d8-\u17db\u17dd\u1800-\u180e\u18a9\u1920-\u192b\u1930-\u193b\u1940\u1944-\u1945\u19b0-\u19c0\u19c8-\u19c9\u19de-\u19ff\u1a17-\u1a1b\u1a1e-\u1a1f\u1a55-\u1a5e\u1a60-\u1a7c\u1a7f\u1aa0-\u1aa6\u1aa8-\u1aad\u1b00-\u1b04\u1b34-\u1b44\u1b5a-\u1b7c\u1b80-\u1b82\u1ba1-\u1bad\u1be6-\u1bf3\u1bfc-\u1bff\u1c24-\u1c37\u1c3b-\u1c3f\u1c7e-\u1c7f\u1cc0-\u1cc7\u1cd0-\u1ce8\u1ced\u1cf2-\u1cf4\u1dc0-\u1de6\u1dfc-\u1dff\u1fbd\u1fbf-\u1fc1\u1fcd-\u1fcf\u1fdd-\u1fdf\u1fed-\u1fef\u1ffd-\u1ffe\u2000-\u2064\u206a-\u206f\u207a-\u207e\u208a-\u208e\u20a0-\u20b9\u20d0-\u20f0\u2100-\u2101\u2103-\u2106\u2108-\u2109\u2114\u2116-\u2118\u211e-\u2123\u2125\u2127\u2129\u212e\u213a-\u213b\u2140-\u2144\u214a-\u214d\u214f\u2190-\u23f3\u2400-\u2426\u2440-\u244a\u249c-\u24e9\u2500-\u26ff\u2701-\u2775\u2794-\u2b4c\u2b50-\u2b59\u2ce5-\u2cea\u2cef-\u2cf1\u2cf9-\u2cfc\u2cfe-\u2cff\u2d70\u2d7f\u2de0-\u2e2e\u2e30-\u2e3b\u2e80-\u2e99\u2e9b-\u2ef3\u2f00-\u2fd5\u2ff0-\u2ffb\u3000-\u3004\u3008-\u3020\u302a-\u3030\u3036-\u3037\u303d-\u303f\u3099-\u309c\u30a0\u30fb\u3190-\u3191\u3196-\u319f\u31c0-\u31e3\u3200-\u321e\u322a-\u3247\u3250\u3260-\u327f\u328a-\u32b0\u32c0-\u32fe\u3300-\u33ff\u4dc0-\u4dff\ua490-\ua4c6\ua4fe-\ua4ff\ua60d-\ua60f\ua66f-\ua67e\ua69f\ua6f0-\ua6f7\ua700-\ua716\ua720-\ua721\ua789-\ua78a\ua802\ua806\ua80b\ua823-\ua82b\ua836-\ua839\ua874-\ua877\ua880-\ua881\ua8b4-\ua8c4\ua8ce-\ua8cf\ua8e0-\ua8f1\ua8f8-\ua8fa\ua926-\ua92f\ua947-\ua953\ua95f\ua980-\ua983\ua9b3-\ua9cd\ua9de-\ua9df\uaa29-\uaa36\uaa43\uaa4c-\uaa4d\uaa5c-\uaa5f\uaa77-\uaa79\uaa7b\uaab0\uaab2-\uaab4\uaab7-\uaab8\uaabe-\uaabf\uaac1\uaade-\uaadf\uaaeb-\uaaf1\uaaf5-\uaaf6\uabe3-\uabed\ufb1e\ufb29\ufbb2-\ufbc1\ufd3e-\ufd3f\ufdfc-\ufdfd\ufe00-\ufe19\ufe20-\ufe26\ufe30-\ufe52\ufe54-\ufe66\ufe68-\ufe6b\ufeff\uff01-\uff0f\uff1a-\uff20\uff3b-\uff40\uff5b-\uff65\uffe0-\uffe6\uffe8-\uffee\ufff9-\uffff\U00010100-\U00010102\U00010137-\U0001013f\U00010179-\U00010189\U00010190-\U0001019b\U000101d0-\U000101fd\U0001039f\U000103d0\U00010857\U0001091f\U0001093f\U00010a01-\U00010a03\U00010a05-\U00010a06\U00010a0c-\U00010a0f\U00010a38-\U00010a3a\U00010a3f\U00010a50-\U00010a58\U00010a7f\U00010b39-\U00010b3f\U00011000-\U00011002\U00011038-\U0001104d\U00011080-\U00011082\U000110b0-\U000110c1\U00011100-\U00011102\U00011127-\U00011134\U00011140-\U00011143\U00011180-\U00011182\U000111b3-\U000111c0\U000111c5-\U000111c8\U000116ab-\U000116b7\U00012470-\U00012473\U00016f51-\U00016f7e\U00016f8f-\U00016f92\U0001d000-\U0001d0f5\U0001d100-\U0001d126\U0001d129-\U0001d1dd\U0001d200-\U0001d245\U0001d300-\U0001d356\U0001d6c1\U0001d6db\U0001d6fb\U0001d715\U0001d735\U0001d74f\U0001d76f\U0001d789\U0001d7a9\U0001d7c3\U0001eef0-\U0001eef1\U0001f000-\U0001f02b\U0001f030-\U0001f093\U0001f0a0-\U0001f0ae\U0001f0b1-\U0001f0be\U0001f0c1-\U0001f0cf\U0001f0d1-\U0001f0df\U0001f110-\U0001f12e\U0001f130-\U0001f16b\U0001f170-\U0001f19a\U0001f1e6-\U0001f202\U0001f210-\U0001f23a\U0001f240-\U0001f248\U0001f250-\U0001f251\U0001f300-\U0001f320\U0001f330-\U0001f335\U0001f337-\U0001f37c\U0001f380-\U0001f393\U0001f3a0-\U0001f3c4\U0001f3c6-\U0001f3ca\U0001f3e0-\U0001f3f0\U0001f400-\U0001f43e\U0001f440\U0001f442-\U0001f4f7\U0001f4f9-\U0001f4fc\U0001f500-\U0001f53d\U0001f540-\U0001f543\U0001f550-\U0001f567\U0001f5fb-\U0001f640\U0001f645-\U0001f64f\U0001f680-\U0001f6c5\U0001f700-\U0001f773\U000e0001\U000e0020-\U000e007f\U000e0100-\U000e01ef]+') WITH ORDINALITY AS t(token, position)
    ) AS tokens
    WHERE folded <> ''
$$;

-- token -> number of occurrences in `tokens`, for single-term frequencies.
CREATE FUNCTION tam_fts_counts(tokens text[]) RETURNS jsonb
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT COALESCE(jsonb_object_agg(token, occurrences), '{}')
    FROM (SELECT token, count(*) AS occurrences FROM unnest(tokens) AS token GROUP BY token) AS counted
$$;

-- Occurrences of `phrase` (consecutive tokens; with `prefix` its last token only
-- has to start the document token) in the token array `document`: FTS5's
-- per-column phrase frequency.
CREATE FUNCTION tam_fts_tf(document text[], phrase text[], prefix boolean) RETURNS integer
LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE AS $$
DECLARE
    phrase_length integer := cardinality(phrase);
    starts integer[];
    step integer;
BEGIN
    IF document IS NULL OR phrase IS NULL OR phrase_length = 0 THEN
        RETURN 0;
    END IF;
    IF phrase_length = 1 AND prefix THEN
        RETURN (SELECT count(*) FROM unnest(document) AS token WHERE starts_with(token, phrase[1]));
    END IF;
    starts := array_positions(document, phrase[1]);
    FOR step IN 2 .. phrase_length LOOP
        EXIT WHEN cardinality(starts) = 0;
        IF prefix AND step = phrase_length THEN
            starts := ARRAY(SELECT start FROM unnest(starts) AS start
                            WHERE starts_with(document[start + step - 1], phrase[step]));
        ELSE
            starts := ARRAY(SELECT start FROM unnest(starts) AS start
                            WHERE document[start + step - 1] = phrase[step]);
        END IF;
    END LOOP;
    RETURN cardinality(starts);
END
$$;

-- ─── Tables and indexes ────────────────────────────────────────────────────
-- Every btree key on a nullable column or expression is declared with SQLite's NULL
-- placement for its direction (ascending NULLS FIRST, descending NULLS LAST);
-- tam_db's translator appends the same clause to such ORDER BY terms, so an index
-- scan in either direction yields SQLite's order. Keys on NOT NULL columns keep the
-- default: the translator adds no clause for them, and a NULLS clause would stop
-- the index (and the primary key's) from serving the reverse direction.

CREATE TABLE sessions (
    id text PRIMARY KEY,
    started_at text NOT NULL,
    ended_at text,
    project text DEFAULT 'general',
    status text DEFAULT 'open',
    summary text,
    log_count bigint DEFAULT 0,
    branch text DEFAULT ''
);
CREATE INDEX idx_s_started ON sessions(started_at);

CREATE TABLE knowledge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    type text NOT NULL,
    content text NOT NULL,
    context text DEFAULT '',
    project text DEFAULT 'general',
    tags text DEFAULT '[]',
    status text DEFAULT 'active',
    superseded_by bigint,
    confidence double precision DEFAULT 1.0,
    source text DEFAULT 'explicit',
    created_at text NOT NULL,
    last_confirmed text,
    recall_count bigint DEFAULT 0,
    last_recalled text,
    branch text DEFAULT '',
    importance text NOT NULL DEFAULT 'medium',
    agent_id text DEFAULT NULL,
    parent_agent_id text DEFAULT NULL,
    source_format text NOT NULL DEFAULT 'auto',
    fts_project text GENERATED ALWAYS AS (tam_fts_project_token(project)) STORED,
    CHECK (source_format IN ('auto','conversation'))
);
CREATE INDEX idx_k_status ON knowledge(status NULLS FIRST);
CREATE INDEX idx_k_type ON knowledge(type);
CREATE INDEX idx_k_project ON knowledge(project NULLS FIRST);
CREATE INDEX idx_k_session ON knowledge(session_id);
CREATE INDEX idx_k_last_confirmed ON knowledge(last_confirmed NULLS FIRST);
CREATE INDEX idx_knowledge_importance ON knowledge(importance);
CREATE INDEX idx_knowledge_status_quality ON knowledge(status NULLS FIRST) WHERE status = 'quality_dropped';
CREATE INDEX idx_k_agent_id ON knowledge(agent_id NULLS FIRST) WHERE agent_id IS NOT NULL;
CREATE INDEX idx_k_parent_agent_id ON knowledge(parent_agent_id NULLS FIRST) WHERE parent_agent_id IS NOT NULL;
CREATE INDEX idx_knowledge_neighbors ON knowledge(project NULLS FIRST, session_id, status NULLS FIRST, created_at, id);

CREATE TABLE relations (
    from_id bigint,
    to_id bigint,
    type text,
    created_at text
);
CREATE INDEX idx_rel_from ON relations(from_id NULLS FIRST);
CREATE INDEX idx_rel_to ON relations(to_id NULLS FIRST);

CREATE TABLE timeline (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    ts text NOT NULL,
    event text NOT NULL,
    summary text NOT NULL,
    details text DEFAULT '',
    project text DEFAULT 'general',
    files text DEFAULT '[]'
);
CREATE INDEX idx_t_session ON timeline(session_id);

CREATE TABLE embeddings (
    knowledge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binary_vector bytea NOT NULL,
    float32_vector bytea NOT NULL,
    embed_model text NOT NULL,
    embed_dim bigint NOT NULL,
    created_at text NOT NULL,
    embedding_provider text,
    embedding_space text,
    content_type text,
    language text,
    embedding vector
);
CREATE INDEX idx_embeddings_space ON embeddings(embedding_space NULLS FIRST);
CREATE INDEX idx_embeddings_provider ON embeddings(embedding_provider NULLS FIRST);

CREATE TABLE errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    category text NOT NULL,
    severity text NOT NULL DEFAULT 'medium',
    description text NOT NULL,
    context text DEFAULT '',
    fix text DEFAULT '',
    project text DEFAULT 'general',
    tags text DEFAULT '[]',
    status text DEFAULT 'open',
    resolved_at text,
    insight_id bigint,
    created_at text NOT NULL
);
CREATE INDEX idx_e_category ON errors(category);
CREATE INDEX idx_e_project ON errors(project NULLS FIRST);
CREATE INDEX idx_e_status ON errors(status NULLS FIRST);
CREATE INDEX idx_e_session ON errors(session_id);
CREATE INDEX idx_e_created ON errors(created_at DESC);

CREATE TABLE insights (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    content text NOT NULL,
    context text DEFAULT '',
    category text NOT NULL,
    importance bigint NOT NULL DEFAULT 2,
    confidence double precision NOT NULL DEFAULT 0.5,
    source_error_ids text DEFAULT '[]',
    project text DEFAULT 'general',
    tags text DEFAULT '[]',
    status text DEFAULT 'active',
    promoted_to_rule_id bigint,
    fire_count bigint DEFAULT 0,
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX idx_i_status ON insights(status NULLS FIRST);
CREATE INDEX idx_i_category ON insights(category);
CREATE INDEX idx_i_project ON insights(project NULLS FIRST);
CREATE INDEX idx_i_importance ON insights(importance DESC);

CREATE TABLE rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    content text NOT NULL,
    context text DEFAULT '',
    category text NOT NULL,
    scope text DEFAULT 'global',
    priority bigint NOT NULL DEFAULT 5,
    source_insight_id bigint,
    project text DEFAULT 'general',
    tags text DEFAULT '[]',
    status text DEFAULT 'active',
    fire_count bigint DEFAULT 0,
    success_count bigint DEFAULT 0,
    fail_count bigint DEFAULT 0,
    success_rate double precision DEFAULT 0.0,
    last_fired text,
    created_at text NOT NULL,
    updated_at text NOT NULL
);
CREATE INDEX idx_r_status ON rules(status NULLS FIRST);
CREATE INDEX idx_r_scope ON rules(scope NULLS FIRST);
CREATE INDEX idx_r_priority ON rules(priority DESC);
CREATE INDEX idx_r_project ON rules(project NULLS FIRST);

CREATE TABLE observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL,
    tool_name text NOT NULL,
    observation_type text NOT NULL DEFAULT 'change',
    summary text NOT NULL,
    files_affected text DEFAULT '[]',
    project text DEFAULT 'general',
    branch text DEFAULT '',
    created_at text NOT NULL
);
CREATE INDEX idx_obs_session ON observations(session_id);
CREATE INDEX idx_obs_project ON observations(project NULLS FIRST);
CREATE INDEX idx_obs_type ON observations(observation_type);
CREATE INDEX idx_obs_created ON observations(created_at DESC);

CREATE TABLE migrations (
    version text PRIMARY KEY,
    description text NOT NULL,
    applied_at text NOT NULL
);

CREATE TABLE graph_nodes (
    id text PRIMARY KEY,
    type text NOT NULL,
    name text NOT NULL,
    content text,
    properties text,
    source text,
    importance double precision DEFAULT 0.5,
    first_seen_at text NOT NULL DEFAULT tam_utc_now(),
    last_seen_at text NOT NULL DEFAULT tam_utc_now(),
    mention_count bigint DEFAULT 1,
    status text DEFAULT 'active',
    name_norm text
);
CREATE INDEX idx_graph_nodes_type ON graph_nodes(type);
CREATE INDEX idx_graph_nodes_name ON graph_nodes(name);
CREATE INDEX idx_graph_nodes_status ON graph_nodes(status NULLS FIRST);
CREATE INDEX idx_graph_nodes_importance ON graph_nodes(importance NULLS FIRST);
CREATE INDEX idx_gn_lastseen ON graph_nodes(last_seen_at);
CREATE INDEX idx_graph_nodes_name_norm ON graph_nodes(name_norm NULLS FIRST);
CREATE INDEX idx_graph_nodes_name_norm_type ON graph_nodes(name_norm NULLS FIRST, type);
CREATE INDEX idx_graph_nodes_matchable ON graph_nodes(id, name, type) WHERE status = 'active' AND strpos(name, ':') = 0;

CREATE TABLE graph_edges (
    id text PRIMARY KEY,
    source_id text NOT NULL,
    target_id text NOT NULL,
    relation_type text NOT NULL,
    weight double precision DEFAULT 1.0,
    context text,
    created_at text NOT NULL DEFAULT tam_utc_now(),
    last_reinforced_at text,
    reinforcement_count bigint DEFAULT 0,
    UNIQUE (source_id, target_id, relation_type)
);
CREATE INDEX idx_graph_edges_source ON graph_edges(source_id);
CREATE INDEX idx_graph_edges_target ON graph_edges(target_id);
CREATE INDEX idx_graph_edges_type ON graph_edges(relation_type);
CREATE INDEX idx_graph_edges_weight ON graph_edges(weight NULLS FIRST);
CREATE INDEX idx_ge_lastref ON graph_edges(last_reinforced_at NULLS FIRST);
CREATE INDEX idx_ge_created_at ON graph_edges(created_at);
CREATE INDEX idx_graph_edges_target_type ON graph_edges(target_id, relation_type);
CREATE INDEX idx_graph_edges_source_type ON graph_edges(source_id, relation_type);

CREATE TABLE knowledge_nodes (
    knowledge_id bigint,
    node_id text,
    role text DEFAULT 'related',
    strength double precision DEFAULT 1.0,
    PRIMARY KEY (knowledge_id, node_id)
);
CREATE INDEX idx_knowledge_nodes_kid ON knowledge_nodes(knowledge_id);
CREATE INDEX idx_knowledge_nodes_nid ON knowledge_nodes(node_id);
CREATE INDEX idx_knowledge_nodes_role ON knowledge_nodes(role NULLS FIRST);

CREATE TABLE episodes (
    id text PRIMARY KEY,
    session_id text NOT NULL,
    project text,
    timestamp text NOT NULL DEFAULT tam_utc_now(),
    narrative text NOT NULL,
    approaches_tried text,
    key_insight text,
    outcome text NOT NULL,
    impact_score double precision DEFAULT 0.5,
    frustration_signals bigint DEFAULT 0,
    user_corrections text,
    concepts text,
    entities text,
    tools_used text,
    duration_minutes bigint,
    similar_to text,
    led_to text,
    contradicts text,
    created_at text NOT NULL DEFAULT tam_utc_now(),
    embedding_id text,
    CHECK (outcome IN ('breakthrough', 'failure', 'routine', 'discovery')),
    CHECK (impact_score >= 0.0 AND impact_score <= 1.0)
);
CREATE INDEX idx_episodes_project ON episodes(project NULLS FIRST);
CREATE INDEX idx_episodes_outcome ON episodes(outcome);
CREATE INDEX idx_episodes_impact ON episodes(impact_score NULLS FIRST);
CREATE INDEX idx_episodes_session ON episodes(session_id);
CREATE INDEX idx_episodes_timestamp ON episodes(timestamp);

CREATE TABLE skills (
    id text PRIMARY KEY,
    name text NOT NULL,
    trigger_pattern text NOT NULL,
    steps text NOT NULL,
    anti_patterns text,
    times_used bigint DEFAULT 0,
    success_rate double precision DEFAULT 0.0,
    avg_steps_to_solve double precision,
    version bigint DEFAULT 1,
    learned_from text,
    last_refined_at text,
    projects text,
    stack text,
    related_skills text,
    status text DEFAULT 'draft',
    created_at text NOT NULL DEFAULT tam_utc_now(),
    UNIQUE (name),
    CHECK (status IN ('draft', 'active', 'mastered', 'deprecated'))
);
CREATE INDEX idx_skills_status ON skills(status NULLS FIRST);
CREATE INDEX idx_skills_name ON skills(name);

CREATE TABLE skill_uses (
    id text PRIMARY KEY,
    skill_id text NOT NULL,
    episode_id text,
    success bigint NOT NULL,
    steps_used bigint,
    notes text,
    used_at text NOT NULL DEFAULT tam_utc_now()
);
CREATE INDEX idx_skill_uses_skill ON skill_uses(skill_id);
CREATE INDEX idx_skill_uses_date ON skill_uses(used_at);

CREATE TABLE competencies (
    domain text PRIMARY KEY,
    level double precision DEFAULT 0.5,
    confidence double precision DEFAULT 0.3,
    based_on bigint DEFAULT 0,
    trend text DEFAULT 'unknown',
    last_updated text NOT NULL DEFAULT tam_utc_now(),
    CHECK (level >= 0.0 AND level <= 1.0),
    CHECK (confidence >= 0.0 AND confidence <= 1.0),
    CHECK (trend IN ('improving', 'stable', 'declining', 'stable_low', 'unknown'))
);

CREATE TABLE blind_spots (
    id text PRIMARY KEY,
    description text NOT NULL,
    domains text,
    evidence text,
    severity double precision DEFAULT 0.5,
    status text DEFAULT 'active',
    discovered_at text NOT NULL DEFAULT tam_utc_now(),
    resolved_at text,
    CHECK (severity >= 0.0 AND severity <= 1.0),
    CHECK (status IN ('active', 'resolved', 'monitoring'))
);
CREATE INDEX idx_blind_spots_status ON blind_spots(status NULLS FIRST);

CREATE TABLE user_model (
    key text PRIMARY KEY,
    value text NOT NULL,
    confidence double precision DEFAULT 0.5,
    evidence_count bigint DEFAULT 1,
    last_updated text NOT NULL DEFAULT tam_utc_now()
);

CREATE TABLE ingest_queue (
    id text PRIMARY KEY,
    source text NOT NULL,
    content_type text NOT NULL,
    raw_content bytea,
    text_content text,
    metadata text,
    status text DEFAULT 'pending',
    error_message text,
    created_at text NOT NULL DEFAULT tam_utc_now(),
    processed_at text,
    CHECK (status IN ('pending', 'processing', 'stored', 'error'))
);
CREATE INDEX idx_ingest_status ON ingest_queue(status NULLS FIRST);
CREATE INDEX idx_ingest_created ON ingest_queue(created_at);

CREATE TABLE reflection_reports (
    id text PRIMARY KEY,
    period_start text NOT NULL,
    period_end text NOT NULL,
    type text NOT NULL,
    new_nodes bigint DEFAULT 0,
    patterns_found bigint DEFAULT 0,
    skills_refined bigint DEFAULT 0,
    rules_proposed bigint DEFAULT 0,
    contradictions bigint DEFAULT 0,
    archived bigint DEFAULT 0,
    focus_areas text,
    key_findings text,
    proposed_changes text,
    created_at text NOT NULL DEFAULT tam_utc_now(),
    CHECK (type IN ('session', 'periodic', 'weekly', 'manual'))
);
CREATE INDEX idx_reflection_type ON reflection_reports(type);
CREATE INDEX idx_reflection_period ON reflection_reports(period_end);

CREATE TABLE pending_proposals (
    id text PRIMARY KEY,
    type text NOT NULL,
    content text NOT NULL,
    evidence text,
    confidence double precision,
    status text DEFAULT 'pending',
    created_at text NOT NULL DEFAULT tam_utc_now(),
    reviewed_at text,
    CHECK (type IN ('rule', 'skill', 'claude_md_update', 'blind_spot')),
    CHECK (status IN ('pending', 'approved', 'rejected'))
);
CREATE INDEX idx_proposals_status ON pending_proposals(status NULLS FIRST);
CREATE INDEX idx_proposals_type ON pending_proposals(type);

CREATE TABLE knowledge_representations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    representation text NOT NULL,
    content text NOT NULL,
    binary_vector bytea NOT NULL,
    float32_vector bytea NOT NULL,
    embed_model text NOT NULL,
    embed_dim bigint NOT NULL,
    created_at text NOT NULL,
    parent_content_hash text,
    last_confirmed text,
    UNIQUE (knowledge_id, representation)
);
CREATE INDEX idx_krepr_kid ON knowledge_representations(knowledge_id);
CREATE INDEX idx_krepr_type ON knowledge_representations(representation);
CREATE INDEX idx_krepr_kid_type ON knowledge_representations(knowledge_id, representation);
CREATE INDEX idx_krepr_repr_kid ON knowledge_representations(representation, knowledge_id);
CREATE INDEX idx_krepr_hash ON knowledge_representations(parent_content_hash NULLS FIRST);

CREATE TABLE triple_extraction_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at text NOT NULL,
    claimed_at text,
    processed_at text,
    UNIQUE (knowledge_id, status)
);
CREATE INDEX idx_teq_status ON triple_extraction_queue(status);
CREATE INDEX idx_teq_created ON triple_extraction_queue(created_at);
CREATE INDEX idx_teq_status_id ON triple_extraction_queue(status, id);

CREATE TABLE knowledge_enrichment (
    knowledge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entities text NOT NULL DEFAULT '[]',
    intent text NOT NULL DEFAULT 'unknown',
    topics text NOT NULL DEFAULT '[]',
    updated_at text NOT NULL
);
CREATE INDEX idx_kenr_intent ON knowledge_enrichment(intent);

CREATE TABLE deep_enrichment_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at text NOT NULL,
    claimed_at text,
    processed_at text,
    UNIQUE (knowledge_id, status)
);
CREATE INDEX idx_deq_status ON deep_enrichment_queue(status);
CREATE INDEX idx_deq_created ON deep_enrichment_queue(created_at);
CREATE INDEX idx_deq_status_id ON deep_enrichment_queue(status, id);

CREATE TABLE representations_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    attempts bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at text NOT NULL,
    claimed_at text,
    processed_at text,
    UNIQUE (knowledge_id, status)
);
CREATE INDEX idx_repq_status ON representations_queue(status);
CREATE INDEX idx_repq_created ON representations_queue(created_at);
CREATE INDEX idx_repq_status_id ON representations_queue(status, id);

CREATE TABLE filter_savings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    filter_name text NOT NULL,
    input_chars bigint NOT NULL,
    output_chars bigint NOT NULL,
    reduction_pct double precision NOT NULL,
    safety text NOT NULL DEFAULT 'strict',
    created_at text NOT NULL
);
CREATE INDEX idx_fs_kid ON filter_savings(knowledge_id);
CREATE INDEX idx_fs_name ON filter_savings(filter_name);
CREATE INDEX idx_fs_at ON filter_savings(created_at);

CREATE TABLE fact_assertions (
    id text PRIMARY KEY,
    subject text NOT NULL,
    predicate text NOT NULL,
    object text NOT NULL,
    subject_name text,
    object_name text,
    confidence double precision NOT NULL DEFAULT 1.0,
    context text,
    source text DEFAULT 'auto',
    project text DEFAULT 'general',
    valid_from text NOT NULL DEFAULT tam_utc_now(),
    valid_to text,
    superseded_by text,
    invalidation_reason text,
    created_at text NOT NULL DEFAULT tam_utc_now(),
    CHECK (confidence >= 0.0 AND confidence <= 1.0)
);
CREATE INDEX idx_fa_spo ON fact_assertions(subject, predicate, object);
CREATE INDEX idx_fa_subject ON fact_assertions(subject);
CREATE INDEX idx_fa_object ON fact_assertions(object);
CREATE INDEX idx_fa_predicate ON fact_assertions(predicate);
CREATE INDEX idx_fa_valid_from ON fact_assertions(valid_from);
CREATE INDEX idx_fa_valid_to ON fact_assertions(valid_to NULLS FIRST);
CREATE INDEX idx_fa_project ON fact_assertions(project NULLS FIRST);
CREATE INDEX idx_fa_current ON fact_assertions(subject, predicate, object) WHERE valid_to IS NULL;

CREATE TABLE workflows (
    id text PRIMARY KEY,
    name text NOT NULL,
    description text,
    trigger_pattern text,
    steps text NOT NULL,
    context text,
    project text DEFAULT 'general',
    source text DEFAULT 'learned',
    times_run bigint DEFAULT 0,
    success_count bigint DEFAULT 0,
    failure_count bigint DEFAULT 0,
    success_rate double precision DEFAULT 0.0,
    avg_duration_ms bigint,
    last_run_at text,
    status text DEFAULT 'active',
    created_at text NOT NULL DEFAULT tam_utc_now(),
    updated_at text NOT NULL DEFAULT tam_utc_now()
);
CREATE INDEX idx_wf_name ON workflows(name);
CREATE INDEX idx_wf_project ON workflows(project NULLS FIRST);
CREATE INDEX idx_wf_status ON workflows(status NULLS FIRST);
CREATE INDEX idx_wf_success_rate ON workflows(success_rate NULLS FIRST);

CREATE TABLE workflow_runs (
    id text PRIMARY KEY,
    workflow_id text NOT NULL,
    session_id text,
    outcome text NOT NULL,
    duration_ms bigint,
    context text,
    error_details text,
    notes text,
    started_at text NOT NULL DEFAULT tam_utc_now(),
    ended_at text,
    CHECK (outcome IN ('success', 'failure', 'partial', 'aborted'))
);
CREATE INDEX idx_wfr_workflow ON workflow_runs(workflow_id);
CREATE INDEX idx_wfr_outcome ON workflow_runs(outcome);
CREATE INDEX idx_wfr_started ON workflow_runs(started_at);
CREATE INDEX idx_wfr_session ON workflow_runs(session_id NULLS FIRST);

CREATE TABLE session_summaries (
    id text PRIMARY KEY,
    session_id text NOT NULL,
    project text DEFAULT 'general',
    branch text,
    summary text NOT NULL,
    highlights text,
    pitfalls text,
    next_steps text,
    open_questions text,
    context_blob text,
    started_at text,
    ended_at text NOT NULL DEFAULT tam_utc_now(),
    consumed bigint DEFAULT 0,
    created_at text NOT NULL DEFAULT tam_utc_now()
);
CREATE INDEX idx_ss_project ON session_summaries(project NULLS FIRST);
CREATE INDEX idx_ss_ended_at ON session_summaries(ended_at DESC);
CREATE INDEX idx_ss_consumed ON session_summaries(consumed NULLS FIRST);
CREATE INDEX idx_ss_session ON session_summaries(session_id);

CREATE TABLE privacy_counters (
    key text PRIMARY KEY,
    value bigint NOT NULL DEFAULT 0,
    updated_at text NOT NULL
);

CREATE TABLE task_phases (
    task_id text NOT NULL,
    phase text NOT NULL,
    entered_at text NOT NULL,
    exited_at text,
    artifacts_json text,
    notes text,
    PRIMARY KEY (task_id, phase, entered_at)
);
CREATE INDEX idx_task_phases_task ON task_phases(task_id);
CREATE INDEX idx_task_phases_current ON task_phases(task_id) WHERE exited_at IS NULL;

CREATE TABLE intents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text,
    project text,
    prompt text NOT NULL,
    created_at text NOT NULL,
    turn_index bigint,
    prompt_hash text NOT NULL
);
CREATE INDEX idx_intents_session ON intents(session_id NULLS FIRST);
CREATE INDEX idx_intents_project ON intents(project NULLS FIRST, created_at);
CREATE INDEX idx_intents_hash ON intents(prompt_hash);

CREATE TABLE embedding_cache (
    key text PRIMARY KEY,
    embedding bytea NOT NULL,
    created_at text NOT NULL,
    model text NOT NULL,
    dim bigint NOT NULL
);
CREATE INDEX idx_embedding_cache_model ON embedding_cache(model);
CREATE INDEX idx_embedding_cache_created ON embedding_cache(created_at);

CREATE TABLE quality_gate_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at text NOT NULL,
    decision text NOT NULL,
    score_total double precision,
    score_specificity double precision,
    score_actionability double precision,
    score_verifiability double precision,
    threshold double precision NOT NULL,
    project text,
    type text,
    content_chars bigint NOT NULL,
    content_preview text NOT NULL,
    reason text,
    knowledge_id bigint,
    provider text,
    model text,
    latency_ms bigint,
    CHECK (decision IN ('pass', 'drop', 'skip', 'error'))
);
CREATE INDEX idx_quality_gate_log_decision ON quality_gate_log(decision);
CREATE INDEX idx_quality_gate_log_created ON quality_gate_log(created_at);

CREATE TABLE contradiction_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at text NOT NULL,
    new_knowledge_id bigint NOT NULL,
    candidate_knowledge_id bigint NOT NULL,
    cosine_similarity double precision NOT NULL,
    llm_confidence double precision,
    decision text NOT NULL,
    reason text,
    provider text,
    model text,
    latency_ms bigint,
    CHECK (decision IN ('superseded', 'flagged', 'rejected', 'skip', 'error'))
);
CREATE INDEX idx_contradiction_log_new ON contradiction_log(new_knowledge_id);
CREATE INDEX idx_contradiction_log_candidate ON contradiction_log(candidate_knowledge_id);
CREATE INDEX idx_contradiction_log_decision ON contradiction_log(decision);
CREATE INDEX idx_contradiction_log_created ON contradiction_log(created_at);

CREATE TABLE write_intents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_uuid text NOT NULL,
    session_id text,
    content_hash text NOT NULL,
    payload_json text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    knowledge_id bigint,
    attempts bigint NOT NULL DEFAULT 0,
    last_error text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    committed_at text,
    UNIQUE (intent_uuid),
    CHECK (status IN ('pending','committed','failed','superseded'))
);
CREATE INDEX idx_write_intents_status ON write_intents(status);
CREATE INDEX idx_write_intents_hash ON write_intents(content_hash);
CREATE INDEX idx_write_intents_session ON write_intents(session_id NULLS FIRST);
CREATE INDEX idx_write_intents_created ON write_intents(created_at);

CREATE TABLE entity_dedup_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at text NOT NULL,
    knowledge_id bigint,
    project text,
    input_tag text NOT NULL,
    matched_node_id text,
    canonical_name text,
    similarity double precision NOT NULL,
    threshold double precision NOT NULL,
    decision text NOT NULL,
    reason text,
    CHECK (decision IN ('merged', 'considered', 'no_match', 'error'))
);
CREATE INDEX idx_entity_dedup_log_decision ON entity_dedup_log(decision);
CREATE INDEX idx_entity_dedup_log_created ON entity_dedup_log(created_at);
CREATE INDEX idx_entity_dedup_log_knowledge ON entity_dedup_log(knowledge_id NULLS FIRST);

CREATE TABLE enrichment_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    session_id text,
    project text NOT NULL DEFAULT 'general',
    ktype text NOT NULL,
    content_snapshot text NOT NULL,
    tags_snapshot text NOT NULL DEFAULT '[]',
    importance text NOT NULL DEFAULT 'medium',
    skip_quality bigint NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'pending',
    attempts bigint NOT NULL DEFAULT 0,
    last_error text,
    enqueued_at text NOT NULL,
    started_at text,
    finished_at text,
    lease_token text,
    heartbeat_at text,
    atomic_only bigint NOT NULL DEFAULT 0,
    CHECK (status IN ('pending', 'processing', 'done', 'failed'))
);
CREATE INDEX idx_eq_status ON enrichment_queue(status);
CREATE INDEX idx_eq_knowledge ON enrichment_queue(knowledge_id);
CREATE INDEX idx_eq_enqueued ON enrichment_queue(enqueued_at);
CREATE INDEX idx_eq_lease ON enrichment_queue(status, heartbeat_at NULLS FIRST);

CREATE TABLE embedding_cache_v11 (
    cache_key text PRIMARY KEY,
    provider text NOT NULL,
    model text NOT NULL,
    embedding_space text NOT NULL,
    dim bigint NOT NULL,
    vector_blob bytea NOT NULL,
    hit_count bigint NOT NULL DEFAULT 0,
    last_used_at text NOT NULL,
    created_at text NOT NULL
);
CREATE INDEX idx_emb_cache_v11_last_used ON embedding_cache_v11(last_used_at);
CREATE INDEX idx_emb_cache_v11_space ON embedding_cache_v11(embedding_space);

CREATE TABLE episodes_v11 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project text NOT NULL,
    session_id text,
    started_at text NOT NULL,
    ended_at text NOT NULL,
    participants text,
    location text,
    summary text NOT NULL,
    outcome text,
    embedding_blob bytea,
    created_at text NOT NULL DEFAULT tam_utc_now_ms()
);
CREATE INDEX idx_episodes_v11_project_time ON episodes_v11(project, started_at);
CREATE INDEX idx_episodes_v11_session ON episodes_v11(session_id NULLS FIRST);
CREATE UNIQUE INDEX idx_episodes_v11_unique ON episodes_v11(project, COALESCE(session_id, '') NULLS FIRST, started_at);

CREATE TABLE episode_facts (
    episode_id bigint NOT NULL,
    knowledge_id bigint NOT NULL,
    PRIMARY KEY (episode_id, knowledge_id)
);
CREATE INDEX idx_episode_facts_kid ON episode_facts(knowledge_id);

CREATE TABLE canonical_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project text NOT NULL,
    type text NOT NULL,
    name text NOT NULL,
    name_norm text NOT NULL,
    embedding bytea,
    attrs text,
    created_at text NOT NULL DEFAULT tam_utc_now_ms(),
    UNIQUE (project, type, name_norm)
);
CREATE INDEX idx_canon_proj_type ON canonical_entities(project, type);

CREATE TABLE entity_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_id bigint NOT NULL,
    alias text NOT NULL,
    alias_norm text NOT NULL,
    source text,
    confidence double precision DEFAULT 1.0,
    created_at text NOT NULL DEFAULT tam_utc_now_ms()
);
CREATE INDEX idx_aliases_norm ON entity_aliases(alias_norm);
CREATE INDEX idx_aliases_canon ON entity_aliases(canonical_id);

CREATE TABLE project_activity (
    project text PRIMARY KEY,
    last_touched_at text NOT NULL,
    touch_count_24h bigint NOT NULL DEFAULT 0,
    updated_at text NOT NULL DEFAULT tam_utc_now_ms()
);
CREATE INDEX idx_proj_activity_touched ON project_activity(last_touched_at);

CREATE TABLE consolidation_state (
    project text PRIMARY KEY,
    last_consolidated_at text,
    last_status text,
    last_error text,
    locked_until text,
    stats_json text,
    updated_at text NOT NULL DEFAULT tam_utc_now_ms()
);
CREATE INDEX idx_consol_locked ON consolidation_state(locked_until NULLS FIRST);

CREATE TABLE atomic_facts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    subject text NOT NULL,
    predicate text NOT NULL,
    object text NOT NULL,
    temporal_text text NOT NULL DEFAULT '',
    content text NOT NULL,
    observed_at text NOT NULL DEFAULT '',
    event_start text NOT NULL DEFAULT '',
    event_end text NOT NULL DEFAULT '',
    event_precision text NOT NULL DEFAULT 'unknown',
    event_key text NOT NULL DEFAULT '',
    temporal_anchor_at text NOT NULL DEFAULT '',
    UNIQUE (knowledge_id, subject, predicate, object, temporal_text)
);
CREATE INDEX idx_atomic_parent ON atomic_facts(knowledge_id);
CREATE INDEX idx_atomic_event_time ON atomic_facts(event_start, event_end);

CREATE TABLE atomic_fact_sources (
    fact_id bigint NOT NULL,
    knowledge_id bigint NOT NULL,
    quote text NOT NULL,
    PRIMARY KEY (fact_id, knowledge_id)
);
CREATE INDEX idx_atomic_source ON atomic_fact_sources(knowledge_id);

CREATE TABLE atomic_fact_runs (
    knowledge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_content text NOT NULL,
    fact_count bigint NOT NULL,
    model text NOT NULL
);

CREATE TABLE atomic_fact_dependencies (
    target_id bigint NOT NULL,
    source_id bigint NOT NULL,
    PRIMARY KEY (target_id, source_id)
);
CREATE INDEX idx_atomic_dependency_source ON atomic_fact_dependencies(source_id);

CREATE TABLE atomic_fact_rebuild (
    knowledge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE knowledge_nodes_quarantine (
    knowledge_id bigint,
    node_id text,
    role text,
    strength double precision,
    reason text NOT NULL,
    archived_at text NOT NULL
);

CREATE TABLE vector_index_revision (
    singleton bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision bigint NOT NULL DEFAULT 0,
    CHECK (singleton = 1)
);

CREATE TABLE passage_sources (
    knowledge_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint text NOT NULL,
    model text NOT NULL
);

CREATE TABLE evidence_passages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id bigint NOT NULL,
    ordinal bigint NOT NULL,
    start_char bigint NOT NULL,
    end_char bigint NOT NULL,
    speaker text NOT NULL,
    content text NOT NULL,
    vector bytea,
    UNIQUE (knowledge_id, ordinal)
);

CREATE TABLE vector_changes (
    seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision bigint NOT NULL,
    knowledge_id bigint NOT NULL
);
CREATE INDEX idx_vector_changes_revision ON vector_changes(revision);

-- ─── Full-text side tables (FTS5 equivalents) ──────────────────────────────
-- One row per indexed source row, id = the FTS5 rowid. Each indexed column is kept
-- three ways: the token array tam_fts_tokens() produces (positions, for phrase and
-- prefix frequencies), its lexemes as a stored tsvector with a GIN index (term and
-- prefix matching), and a token -> occurrences jsonb (single-term frequencies by a
-- binary search instead of an array scan per matched row). doc_length is the row's
-- token count over all FTS5 columns, the document length FTS5's bm25() uses.

CREATE TABLE fts_stats (
    source text PRIMARY KEY,
    doc_count bigint NOT NULL DEFAULT 0,
    total_length bigint NOT NULL DEFAULT 0
);

CREATE TABLE knowledge_tsv (
    id bigint PRIMARY KEY,
    content text[] NOT NULL,
    content_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(content)) STORED,
    content_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(content)) STORED,
    context text[] NOT NULL,
    context_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(context)) STORED,
    context_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(context)) STORED,
    tags text[] NOT NULL,
    tags_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(tags)) STORED,
    tags_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(tags)) STORED,
    fts_project text NOT NULL,
    doc_length integer NOT NULL
);
CREATE INDEX knowledge_tsv_content ON knowledge_tsv USING gin (content_lexemes);
CREATE INDEX knowledge_tsv_context ON knowledge_tsv USING gin (context_lexemes);
CREATE INDEX knowledge_tsv_tags ON knowledge_tsv USING gin (tags_lexemes);
CREATE INDEX knowledge_tsv_fts_project ON knowledge_tsv (fts_project);

CREATE TABLE errors_tsv (
    id bigint PRIMARY KEY,
    description text[] NOT NULL,
    description_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(description)) STORED,
    description_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(description)) STORED,
    context text[] NOT NULL,
    context_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(context)) STORED,
    context_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(context)) STORED,
    fix text[] NOT NULL,
    fix_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(fix)) STORED,
    fix_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(fix)) STORED,
    tags text[] NOT NULL,
    tags_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(tags)) STORED,
    tags_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(tags)) STORED,
    doc_length integer NOT NULL
);
CREATE INDEX errors_tsv_description ON errors_tsv USING gin (description_lexemes);
CREATE INDEX errors_tsv_context ON errors_tsv USING gin (context_lexemes);
CREATE INDEX errors_tsv_fix ON errors_tsv USING gin (fix_lexemes);
CREATE INDEX errors_tsv_tags ON errors_tsv USING gin (tags_lexemes);

CREATE TABLE atomic_facts_tsv (
    id bigint PRIMARY KEY,
    content text[] NOT NULL,
    content_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(content)) STORED,
    content_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(content)) STORED,
    doc_length integer NOT NULL
);
CREATE INDEX atomic_facts_tsv_content ON atomic_facts_tsv USING gin (content_lexemes);

CREATE TABLE evidence_passages_tsv (
    id bigint PRIMARY KEY,
    content text[] NOT NULL,
    content_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(content)) STORED,
    content_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(content)) STORED,
    doc_length integer NOT NULL
);
CREATE INDEX evidence_passages_tsv_content ON evidence_passages_tsv USING gin (content_lexemes);

CREATE TABLE episodes_v11_tsv (
    id bigint PRIMARY KEY,
    summary text[] NOT NULL,
    summary_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(summary)) STORED,
    summary_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(summary)) STORED,
    participants text[] NOT NULL,
    participants_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(participants)) STORED,
    participants_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(participants)) STORED,
    outcome text[] NOT NULL,
    outcome_lexemes tsvector GENERATED ALWAYS AS (array_to_tsvector(outcome)) STORED,
    outcome_counts jsonb GENERATED ALWAYS AS (tam_fts_counts(outcome)) STORED,
    doc_length integer NOT NULL
);
CREATE INDEX episodes_v11_tsv_summary ON episodes_v11_tsv USING gin (summary_lexemes);
CREATE INDEX episodes_v11_tsv_participants ON episodes_v11_tsv USING gin (participants_lexemes);
CREATE INDEX episodes_v11_tsv_outcome ON episodes_v11_tsv USING gin (outcome_lexemes);

INSERT INTO fts_stats (source) VALUES
    ('knowledge_tsv'), ('errors_tsv'), ('atomic_facts_tsv'), ('evidence_passages_tsv'), ('episodes_v11_tsv');

CREATE FUNCTION tam_fts_stats_add(stats_source text, documents integer, tokens bigint) RETURNS void
LANGUAGE sql AS $$
    UPDATE fts_stats SET doc_count = doc_count + documents, total_length = total_length + tokens
    WHERE source = stats_source
$$;

-- knowledge_fts: content, context, tags, fts_project (k_fts_i / k_fts_u / k_fts_d).
CREATE FUNCTION tam_knowledge_fts_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    removed integer;
    added integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        DELETE FROM knowledge_tsv WHERE id = OLD.id RETURNING doc_length INTO removed;
        IF FOUND THEN
            PERFORM tam_fts_stats_add('knowledge_tsv', -1, -removed);
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        INSERT INTO knowledge_tsv (id, content, context, tags, fts_project, doc_length)
        SELECT NEW.id, content, context, tags, project[1],
               cardinality(content) + cardinality(context) + cardinality(tags) + cardinality(project)
        FROM (SELECT tam_fts_tokens(NEW.content) AS content, tam_fts_tokens(NEW.context) AS context,
                     tam_fts_tokens(NEW.tags) AS tags, tam_fts_tokens(NEW.fts_project) AS project) AS tokens
        RETURNING doc_length INTO added;
        PERFORM tam_fts_stats_add('knowledge_tsv', 1, added);
    END IF;
    RETURN NULL;
END
$$;

-- errors_fts: description, context, fix, tags (e_fts_i / e_fts_u / e_fts_d).
CREATE FUNCTION tam_errors_fts_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    removed integer;
    added integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        DELETE FROM errors_tsv WHERE id = OLD.id RETURNING doc_length INTO removed;
        IF FOUND THEN
            PERFORM tam_fts_stats_add('errors_tsv', -1, -removed);
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        INSERT INTO errors_tsv (id, description, context, fix, tags, doc_length)
        SELECT NEW.id, description, context, fix, tags,
               cardinality(description) + cardinality(context) + cardinality(fix) + cardinality(tags)
        FROM (SELECT tam_fts_tokens(NEW.description) AS description, tam_fts_tokens(NEW.context) AS context,
                     tam_fts_tokens(NEW.fix) AS fix, tam_fts_tokens(NEW.tags) AS tags) AS tokens
        RETURNING doc_length INTO added;
        PERFORM tam_fts_stats_add('errors_tsv', 1, added);
    END IF;
    RETURN NULL;
END
$$;

-- atomic_facts_fts: content. atomic_fact_delete also drops the fact's sources,
-- as the SQLite trigger of the same name does.
CREATE FUNCTION tam_atomic_facts_fts_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    removed integer;
    added integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        DELETE FROM atomic_facts_tsv WHERE id = OLD.id RETURNING doc_length INTO removed;
        IF FOUND THEN
            PERFORM tam_fts_stats_add('atomic_facts_tsv', -1, -removed);
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        DELETE FROM atomic_fact_sources WHERE fact_id = OLD.id;
        RETURN NULL;
    END IF;
    INSERT INTO atomic_facts_tsv (id, content, doc_length)
    SELECT NEW.id, content, cardinality(content) FROM (SELECT tam_fts_tokens(NEW.content) AS content) AS tokens
    RETURNING doc_length INTO added;
    PERFORM tam_fts_stats_add('atomic_facts_tsv', 1, added);
    RETURN NULL;
END
$$;

-- evidence_passages_fts: content (evidence_passages_insert / _update / _delete).
CREATE FUNCTION tam_evidence_passages_fts_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    removed integer;
    added integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        DELETE FROM evidence_passages_tsv WHERE id = OLD.id RETURNING doc_length INTO removed;
        IF FOUND THEN
            PERFORM tam_fts_stats_add('evidence_passages_tsv', -1, -removed);
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        INSERT INTO evidence_passages_tsv (id, content, doc_length)
        SELECT NEW.id, content, cardinality(content) FROM (SELECT tam_fts_tokens(NEW.content) AS content) AS tokens
        RETURNING doc_length INTO added;
        PERFORM tam_fts_stats_add('evidence_passages_tsv', 1, added);
    END IF;
    RETURN NULL;
END
$$;

-- episodes_v11_fts: summary, participants, outcome. On SQLite the episode
-- extractor writes the contentless FTS row itself, indexing the participants as
-- the space-joined list and a missing outcome as ''; the column holds the JSON
-- array, so its elements are indexed here.
CREATE FUNCTION tam_fts_participants(participants text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
    SELECT CASE WHEN participants IS JSON ARRAY
                THEN (SELECT string_agg(element, ' ' ORDER BY position)
                      FROM json_array_elements_text(participants::json) WITH ORDINALITY AS e(element, position))
                ELSE participants END
$$;

CREATE FUNCTION tam_episodes_v11_fts_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    removed integer;
    added integer;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        DELETE FROM episodes_v11_tsv WHERE id = OLD.id RETURNING doc_length INTO removed;
        IF FOUND THEN
            PERFORM tam_fts_stats_add('episodes_v11_tsv', -1, -removed);
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN NULL;
    END IF;
    INSERT INTO episodes_v11_tsv (id, summary, participants, outcome, doc_length)
    SELECT NEW.id, summary, participants, outcome,
           cardinality(summary) + cardinality(participants) + cardinality(outcome)
    FROM (SELECT tam_fts_tokens(NEW.summary) AS summary,
                 tam_fts_tokens(tam_fts_participants(NEW.participants)) AS participants,
                 tam_fts_tokens(COALESCE(NEW.outcome, '')) AS outcome) AS tokens
    RETURNING doc_length INTO added;
    PERFORM tam_fts_stats_add('episodes_v11_tsv', 1, added);
    RETURN NULL;
END
$$;

CREATE TRIGGER k_fts_i AFTER INSERT ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_fts_sync();
CREATE TRIGGER k_fts_u AFTER UPDATE OF content, context, tags, project ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_fts_sync();
CREATE TRIGGER k_fts_d AFTER DELETE ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_fts_sync();

CREATE TRIGGER e_fts_i AFTER INSERT ON errors
    FOR EACH ROW EXECUTE FUNCTION tam_errors_fts_sync();
CREATE TRIGGER e_fts_u AFTER UPDATE ON errors
    FOR EACH ROW EXECUTE FUNCTION tam_errors_fts_sync();
CREATE TRIGGER e_fts_d AFTER DELETE ON errors
    FOR EACH ROW EXECUTE FUNCTION tam_errors_fts_sync();

CREATE TRIGGER atomic_fact_insert AFTER INSERT ON atomic_facts
    FOR EACH ROW EXECUTE FUNCTION tam_atomic_facts_fts_sync();
CREATE TRIGGER atomic_fact_update AFTER UPDATE OF content ON atomic_facts
    FOR EACH ROW EXECUTE FUNCTION tam_atomic_facts_fts_sync();
CREATE TRIGGER atomic_fact_delete AFTER DELETE ON atomic_facts
    FOR EACH ROW EXECUTE FUNCTION tam_atomic_facts_fts_sync();

CREATE TRIGGER evidence_passages_insert AFTER INSERT ON evidence_passages
    FOR EACH ROW EXECUTE FUNCTION tam_evidence_passages_fts_sync();
CREATE TRIGGER evidence_passages_update AFTER UPDATE ON evidence_passages
    FOR EACH ROW EXECUTE FUNCTION tam_evidence_passages_fts_sync();
CREATE TRIGGER evidence_passages_delete AFTER DELETE ON evidence_passages
    FOR EACH ROW EXECUTE FUNCTION tam_evidence_passages_fts_sync();

CREATE TRIGGER episodes_v11_fts_insert AFTER INSERT ON episodes_v11
    FOR EACH ROW EXECUTE FUNCTION tam_episodes_v11_fts_sync();
CREATE TRIGGER episodes_v11_fts_update AFTER UPDATE OF summary, participants, outcome ON episodes_v11
    FOR EACH ROW EXECUTE FUNCTION tam_episodes_v11_fts_sync();
CREATE TRIGGER episodes_v11_fts_delete AFTER DELETE ON episodes_v11
    FOR EACH ROW EXECUTE FUNCTION tam_episodes_v11_fts_sync();

-- FTS5 'rebuild': re-derive every side table and fts_stats from the indexed tables
-- (repair, or after rows were loaded with triggers bypassed). Runs in the caller's
-- transaction; memory_core.pg_fts.rebuild() calls it.
CREATE FUNCTION tam_fts_rebuild() RETURNS void
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM knowledge_tsv;
    INSERT INTO knowledge_tsv (id, content, context, tags, fts_project, doc_length)
    SELECT id, content, context, tags, project[1],
           cardinality(content) + cardinality(context) + cardinality(tags) + cardinality(project)
    FROM (SELECT id, tam_fts_tokens(content) AS content, tam_fts_tokens(context) AS context,
                 tam_fts_tokens(tags) AS tags, tam_fts_tokens(fts_project) AS project FROM knowledge) AS tokens;

    DELETE FROM errors_tsv;
    INSERT INTO errors_tsv (id, description, context, fix, tags, doc_length)
    SELECT id, description, context, fix, tags,
           cardinality(description) + cardinality(context) + cardinality(fix) + cardinality(tags)
    FROM (SELECT id, tam_fts_tokens(description) AS description, tam_fts_tokens(context) AS context,
                 tam_fts_tokens(fix) AS fix, tam_fts_tokens(tags) AS tags FROM errors) AS tokens;

    DELETE FROM atomic_facts_tsv;
    INSERT INTO atomic_facts_tsv (id, content, doc_length)
    SELECT id, content, cardinality(content)
    FROM (SELECT id, tam_fts_tokens(content) AS content FROM atomic_facts) AS tokens;

    DELETE FROM evidence_passages_tsv;
    INSERT INTO evidence_passages_tsv (id, content, doc_length)
    SELECT id, content, cardinality(content)
    FROM (SELECT id, tam_fts_tokens(content) AS content FROM evidence_passages) AS tokens;

    DELETE FROM episodes_v11_tsv;
    INSERT INTO episodes_v11_tsv (id, summary, participants, outcome, doc_length)
    SELECT id, summary, participants, outcome, cardinality(summary) + cardinality(participants) + cardinality(outcome)
    FROM (SELECT id, tam_fts_tokens(summary) AS summary,
                 tam_fts_tokens(tam_fts_participants(participants)) AS participants,
                 tam_fts_tokens(COALESCE(outcome, '')) AS outcome FROM episodes_v11) AS tokens;

    UPDATE fts_stats SET doc_count = totals.documents, total_length = totals.tokens
    FROM (
        SELECT 'knowledge_tsv' AS source, count(*) AS documents, COALESCE(sum(doc_length), 0) AS tokens
        FROM knowledge_tsv
        UNION ALL SELECT 'errors_tsv', count(*), COALESCE(sum(doc_length), 0) FROM errors_tsv
        UNION ALL SELECT 'atomic_facts_tsv', count(*), COALESCE(sum(doc_length), 0) FROM atomic_facts_tsv
        UNION ALL SELECT 'evidence_passages_tsv', count(*), COALESCE(sum(doc_length), 0) FROM evidence_passages_tsv
        UNION ALL SELECT 'episodes_v11_tsv', count(*), COALESCE(sum(doc_length), 0) FROM episodes_v11_tsv
    ) AS totals
    WHERE fts_stats.source = totals.source;
END
$$;

-- ─── Graph names (migration 026) ───────────────────────────────────────────
-- SQLite rewrites name_norm in an AFTER trigger; a BEFORE trigger sets the same
-- value without a second write. lower() folds all of Unicode here, SQLite's only
-- ASCII; the Python callers (episodic.py) compare against str.lower().
CREATE FUNCTION tam_graph_nodes_name_norm() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.name_norm := lower(btrim(NEW.name, ' '));
    RETURN NEW;
END
$$;

CREATE TRIGGER graph_nodes_name_norm_ins BEFORE INSERT ON graph_nodes
    FOR EACH ROW EXECUTE FUNCTION tam_graph_nodes_name_norm();
CREATE TRIGGER graph_nodes_name_norm_upd BEFORE UPDATE OF name ON graph_nodes
    FOR EACH ROW EXECUTE FUNCTION tam_graph_nodes_name_norm();

-- ─── Graph link integrity (migration 031) ──────────────────────────────────
CREATE FUNCTION tam_knowledge_nodes_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM knowledge WHERE id = NEW.knowledge_id)
       OR NOT EXISTS (SELECT 1 FROM graph_nodes WHERE id = NEW.node_id) THEN
        RAISE EXCEPTION 'Graph link requires existing knowledge and node';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER knowledge_nodes_insert_guard BEFORE INSERT ON knowledge_nodes
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_nodes_guard();
CREATE TRIGGER knowledge_nodes_update_guard BEFORE UPDATE OF knowledge_id, node_id ON knowledge_nodes
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_nodes_guard();

CREATE FUNCTION tam_knowledge_links_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM knowledge_nodes WHERE knowledge_id = OLD.id;
    RETURN NULL;
END
$$;

CREATE TRIGGER knowledge_links_delete AFTER DELETE ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_knowledge_links_delete();

CREATE FUNCTION tam_node_links_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM knowledge_nodes WHERE node_id = OLD.id;
    RETURN NULL;
END
$$;

CREATE TRIGGER node_links_delete AFTER DELETE ON graph_nodes
    FOR EACH ROW EXECUTE FUNCTION tam_node_links_delete();

CREATE FUNCTION tam_knowledge_links_id_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM knowledge_nodes WHERE knowledge_id = OLD.id) THEN
        RAISE EXCEPTION 'Cannot change linked knowledge identity';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER knowledge_links_id_guard BEFORE UPDATE OF id ON knowledge
    FOR EACH ROW WHEN (OLD.id IS DISTINCT FROM NEW.id) EXECUTE FUNCTION tam_knowledge_links_id_guard();

CREATE FUNCTION tam_node_links_id_guard() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM knowledge_nodes WHERE node_id = OLD.id) THEN
        RAISE EXCEPTION 'Cannot change linked node identity';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER node_links_id_guard BEFORE UPDATE OF id ON graph_nodes
    FOR EACH ROW WHEN (OLD.id IS DISTINCT FROM NEW.id) EXECUTE FUNCTION tam_node_links_id_guard();

-- ─── Atomic facts follow their sources (migration 029 / Store._migrate) ────
CREATE FUNCTION tam_atomic_source_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO atomic_fact_rebuild (knowledge_id)
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id AND target_id <> OLD.id
        ON CONFLICT DO NOTHING;
    DELETE FROM atomic_fact_runs WHERE knowledge_id IN (
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id
    ) OR knowledge_id = OLD.id;
    DELETE FROM atomic_facts WHERE knowledge_id IN (
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id
    ) OR knowledge_id = OLD.id;
    DELETE FROM atomic_fact_dependencies WHERE target_id = OLD.id;
    DELETE FROM atomic_fact_rebuild WHERE knowledge_id = OLD.id;
    RETURN NULL;
END
$$;

CREATE TRIGGER atomic_source_delete AFTER DELETE ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_atomic_source_delete();

CREATE FUNCTION tam_atomic_source_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO atomic_fact_rebuild (knowledge_id)
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id
        ON CONFLICT DO NOTHING;
    INSERT INTO atomic_fact_rebuild (knowledge_id)
        SELECT knowledge_id FROM atomic_fact_runs WHERE knowledge_id = OLD.id
        ON CONFLICT DO NOTHING;
    DELETE FROM atomic_fact_runs WHERE knowledge_id IN (
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id
    ) OR knowledge_id = OLD.id;
    DELETE FROM atomic_facts WHERE knowledge_id IN (
        SELECT target_id FROM atomic_fact_dependencies WHERE source_id = OLD.id
    ) OR knowledge_id = OLD.id;
    RETURN NULL;
END
$$;

CREATE TRIGGER atomic_source_update
    AFTER UPDATE OF content, status, project, session_id, branch, created_at ON knowledge
    FOR EACH ROW WHEN (OLD.content IS DISTINCT FROM NEW.content OR OLD.status IS DISTINCT FROM NEW.status
                       OR OLD.project IS DISTINCT FROM NEW.project OR OLD.session_id IS DISTINCT FROM NEW.session_id
                       OR OLD.branch IS DISTINCT FROM NEW.branch OR OLD.created_at IS DISTINCT FROM NEW.created_at)
    EXECUTE FUNCTION tam_atomic_source_update();

-- ─── Evidence passages follow their sources (migrations 030, 033) ──────────
CREATE FUNCTION tam_evidence_source_invalidate() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM passage_sources WHERE knowledge_id = OLD.id;
    RETURN NULL;
END
$$;

CREATE TRIGGER evidence_source_update
    AFTER UPDATE OF content, status, project, branch, type, source_format ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_evidence_source_invalidate();
CREATE TRIGGER evidence_source_delete AFTER DELETE ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_evidence_source_invalidate();

CREATE FUNCTION tam_passage_source_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM evidence_passages WHERE knowledge_id = OLD.knowledge_id;
    RETURN NULL;
END
$$;

CREATE TRIGGER passage_source_delete AFTER DELETE ON passage_sources
    FOR EACH ROW EXECUTE FUNCTION tam_passage_source_delete();

-- ─── Vector index revision and change log (migrations 032, 036) ────────────
-- Every change to a searchable embedding bumps the revision once per row and logs
-- the affected record ids (an UPDATE logs the old and the new id), keeping the
-- newest 50,000 log rows, as the SQLite triggers do.
CREATE FUNCTION tam_vector_revision_bump() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    kept_changes CONSTANT bigint := 50000;
    current_revision bigint;
    old_record bigint;
    new_record bigint;
BEGIN
    IF TG_TABLE_NAME = 'embeddings' THEN
        IF TG_OP <> 'INSERT' THEN old_record := OLD.knowledge_id; END IF;
        IF TG_OP <> 'DELETE' THEN new_record := NEW.knowledge_id; END IF;
    ELSE
        IF TG_OP <> 'INSERT' THEN old_record := OLD.id; END IF;
        IF TG_OP <> 'DELETE' THEN new_record := NEW.id; END IF;
    END IF;
    UPDATE vector_index_revision SET revision = revision + 1 WHERE singleton = 1
        RETURNING revision INTO current_revision;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    IF old_record IS NOT NULL THEN
        INSERT INTO vector_changes (revision, knowledge_id) VALUES (current_revision, old_record);
    END IF;
    IF new_record IS NOT NULL THEN
        INSERT INTO vector_changes (revision, knowledge_id) VALUES (current_revision, new_record);
    END IF;
    DELETE FROM vector_changes WHERE seq <= (SELECT max(seq) FROM vector_changes) - kept_changes;
    RETURN NULL;
END
$$;

CREATE TRIGGER vector_revision_embedding_insert AFTER INSERT ON embeddings
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();
CREATE TRIGGER vector_revision_embedding_update AFTER UPDATE ON embeddings
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();
CREATE TRIGGER vector_revision_embedding_delete AFTER DELETE ON embeddings
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();
CREATE TRIGGER vector_revision_knowledge_insert AFTER INSERT ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();
CREATE TRIGGER vector_revision_knowledge_update AFTER UPDATE OF id, status, project, type, branch ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();
CREATE TRIGGER vector_revision_knowledge_delete AFTER DELETE ON knowledge
    FOR EACH ROW EXECUTE FUNCTION tam_vector_revision_bump();

-- ─── SQLite -> PostgreSQL migration quarantine (PostgreSQL only) ───────────
-- Rows the migration copier could not place (orphans) are kept here verbatim
-- instead of blocking the migration; purging the workspace drops them with it.
CREATE TABLE migration_quarantine (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_table text NOT NULL,
    source_pk text NOT NULL,
    row jsonb NOT NULL,
    reason text NOT NULL,
    migrated_at text NOT NULL
);
CREATE INDEX idx_migration_quarantine_source ON migration_quarantine (source_table);

-- ─── Rows a fresh SQLite store starts with ─────────────────────────────────
INSERT INTO vector_index_revision (singleton, revision) VALUES (1, 0);
INSERT INTO privacy_counters (key, value, updated_at) VALUES ('private_redactions_total', 0, '1970-01-01T00:00:00Z');
INSERT INTO migrations (version, description, applied_at)
SELECT version, description, tam_utc_now()
FROM (VALUES
    ('001', 'v5 schema'), ('002', 'multi representation'), ('003', 'triple extraction queue'),
    ('004', 'deep enrichment'), ('005', 'representations queue'), ('006', 'filter savings'),
    ('007', 'perf indexes'), ('008', 'temporal kg'), ('009', 'procedural'), ('010', 'session continuity'),
    ('011', 'privacy counters'), ('012', 'task phases'), ('013', 'intents'), ('014', 'embedding cache'),
    ('015', 'quality importance'), ('016', 'contradictions'), ('017', 'outbox'), ('018', 'entity dedup'),
    ('019', 'episodic links'), ('020', 'async enrichment'), ('021', 'embedding spaces'),
    ('022', 'embedding cache v11'), ('023', 'episodes'), ('024', 'entity aliases'),
    ('025', 'consolidation state'), ('026', 'graph nodes dedup'), ('027', 'repr freshness'),
    ('028', 'agent lineage'), ('029', 'atomic facts'), ('030', 'evidence lifecycle'),
    ('031', 'graph link integrity'), ('032', 'vector index revision'), ('033', 'evidence passages'),
    ('034', 'canonical timestamps'), ('035', 'fts project token'), ('036', 'vector change log'),
    ('037', 'graph matchable names')
) AS applied(version, description);
